export const categories = ["Innovation", "Intelligence", "Technologies", "Robotique", "Cybersécurité", "Futur", "Espace", "Sciences"] as const;
export type Category = (typeof categories)[number];

export type Article = {
  slug: string; title: string; excerpt: string; category: Category; format: "FLASH" | "FOCUS" | "VISION" | "RENCONTRE" | "SEMAINE";
  date: string; readingTime: string; featured?: boolean; image: string; takeaway: string[];
};

export const articles: Article[] = [
  { slug: "le-stockage-energie-local", title: "Le stockage local change d’échelle : ce que les batteries de quartier peuvent réellement apporter", excerpt: "Entre autonomie énergétique, résilience des réseaux et contraintes économiques, une nouvelle génération d’infrastructures se dessine.", category: "Innovation", format: "FOCUS", date: "19 septembre 2026", readingTime: "7 min", featured: true, image: "linear-gradient(130deg,#a59b80,#312f27)", takeaway: ["Le stockage rapproche production et consommation d’énergie.", "La technologie doit encore démontrer son modèle économique.", "Les réseaux locaux deviennent plus résilients."] },
  { slug: "modeles-raisonnement", title: "Pourquoi les modèles de raisonnement changent la manière dont les machines résolvent les problèmes", excerpt: "Ces systèmes ne pensent pas comme nous, mais leurs nouvelles méthodes de calcul modifient déjà leurs usages.", category: "Intelligence", format: "FOCUS", date: "18 septembre 2026", readingTime: "6 min", image: "linear-gradient(130deg,#5b6559,#d5d0bc)", takeaway: ["Le raisonnement améliore certains problèmes complexes.", "Il ne garantit pas la fiabilité des réponses.", "Les coûts de calcul restent un enjeu majeur."] },
  { slug: "puces-calcul-local", title: "Les nouvelles puces basse consommation redessinent l’équilibre entre cloud et calcul local", excerpt: "Le traitement embarqué devient assez puissant pour déplacer certaines tâches loin des centres de données.", category: "Technologies", format: "FOCUS", date: "17 septembre 2026", readingTime: "5 min", image: "linear-gradient(130deg,#3e4748,#c6b99f)", takeaway: ["Le calcul local réduit la latence.", "Il peut limiter les transferts de données.", "Le cloud conserve un rôle central pour les tâches lourdes."] },
  { slug: "robots-agricoles", title: "Ces robots agricoles autonomes désherbent sans pesticide", excerpt: "Des machines légères associent vision artificielle et précision mécanique pour intervenir directement dans les cultures.", category: "Robotique", format: "FLASH", date: "16 septembre 2026", readingTime: "3 min", image: "linear-gradient(130deg,#647052,#d2c9a9)", takeaway: ["La vision permet de distinguer cultures et mauvaises herbes.", "La viabilité dépend du coût d’exploitation."] },
  { slug: "signal-quantique", title: "Un signal quantique mesuré à température ambiante ouvre une nouvelle piste de recherche", excerpt: "La découverte est préliminaire, mais elle pourrait faciliter certains dispositifs de mesure de haute précision.", category: "Sciences", format: "FLASH", date: "15 septembre 2026", readingTime: "3 min", image: "linear-gradient(130deg,#2d3439,#a8b0ad)", takeaway: ["Le résultat doit être reproduit par d’autres équipes.", "La recherche fondamentale précède les applications."] },
  { slug: "satellites-desorbitation", title: "Pourquoi les satellites de demain devront prévoir leur propre désorbitation", excerpt: "La gestion des débris spatiaux devient un enjeu industriel et réglementaire incontournable.", category: "Espace", format: "FOCUS", date: "14 septembre 2026", readingTime: "6 min", image: "linear-gradient(130deg,#18222d,#9d9582)", takeaway: ["L’orbite basse est de plus en plus encombrée.", "La désorbitation doit être pensée dès la conception."] },
];

export const getArticlesByCategory = (category: string) => articles.filter((article) => article.category.toLowerCase() === category.toLowerCase());
