import { requireAdmin } from "./_lib/auth.js";

const header='<header class="global-shell-header"><div class="global-shell-inner"><a class="global-shell-brand" href="/">TAMUSNI</a></div></header>';
const rail='<aside class="tamusni-rail" aria-label="Navigation TAMUSNI"><a class="rail-brand" href="/" aria-label="TAMUSNI — Retour à l’accueil" title="Retour à l’accueil">TAMUSNI</a><nav class="tamusni-rail-nav"><a class="rail-item" href="/intelligence-artificielle/" aria-label="Intelligence artificielle" data-label="Intelligence artificielle" title="Intelligence artificielle"><span class="rail-symbol" aria-hidden="true">IA</span></a><a class="rail-item" href="/innovation/" aria-label="Innovation" data-label="Innovation" title="Innovation"><span class="rail-symbol" aria-hidden="true">✦</span></a><a class="rail-item" href="/robotique/" aria-label="Robotique" data-label="Robotique" title="Robotique"><span class="rail-symbol" aria-hidden="true">⚙</span></a><a class="rail-item" href="/cybersecurite/" aria-label="Cybersécurité" data-label="Cybersécurité" title="Cybersécurité"><span class="rail-symbol" aria-hidden="true">◈</span></a><a class="rail-item" href="/espace/" aria-label="Espace" data-label="Espace" title="Espace"><span class="rail-symbol" aria-hidden="true">☼</span></a></nav><div class="tamusni-rail-tools"><select class="rail-language" id="global-language" aria-label="Langue" title="Langue"><option value="fr">FR</option><option value="ar">AR</option><option value="en">EN</option></select><button class="rail-item" id="rail-theme" type="button" aria-label="Changer de thème" data-label="Thème" title="Thème">◐</button><a class="rail-item rail-account rail-symbol" href="/connexion/" aria-label="Inscription et connexion" data-label="Inscription / Connexion" title="Inscription / Connexion">◎</a></div></aside>';
const adminRail='<aside class="tamusni-rail admin-rail" aria-label="Navigation administrateur"><a class="rail-brand admin-rail-brand" href="/" aria-label="TAMUSNI — Voir le site" title="Voir le site">TAMUSNI</a><nav class="tamusni-rail-nav"><button class="rail-item" type="button" data-admin-view="dashboard" data-label="Tableau de bord" aria-label="Tableau de bord" title="Tableau de bord"><span class="rail-symbol" aria-hidden="true">▦</span></button><button class="rail-item" type="button" data-admin-view="notifications" data-label="Notifications" aria-label="Notifications" title="Notifications"><span class="rail-symbol" aria-hidden="true">◉</span><span class="admin-notice-count" hidden></span></button><button class="rail-item" type="button" data-admin-view="accounts" data-label="Comptes" aria-label="Comptes" title="Comptes"><span class="rail-symbol" aria-hidden="true">◎</span></button><button class="rail-item" type="button" data-admin-view="content" data-label="Contenus" aria-label="Contenus" title="Contenus"><span class="rail-symbol" aria-hidden="true">✦</span></button><a class="rail-item" href="/mon-espace/#profile" data-label="Profil et réglages" aria-label="Profil et réglages" title="Profil et réglages"><span class="rail-symbol" aria-hidden="true">◉</span></a></nav><div class="tamusni-rail-tools"><select class="rail-language" id="global-language" aria-label="Langue" title="Langue"><option value="fr">FR</option><option value="ar">AR</option><option value="en">EN</option></select><button class="rail-item" id="rail-theme" type="button" aria-label="Changer de thème" data-label="Thème" title="Thème">◐</button><button class="rail-item" id="admin-logout" type="button" aria-label="Se déconnecter" data-label="Se déconnecter" title="Se déconnecter">↪</button></div></aside>';
const footer='<footer class="global-shell-footer"><div class="global-footer-inner"><div class="global-footer-follow">TAMUSNI</div><div class="global-footer-bottom"><span>© 2026 TAMUSNI · A&amp;B TECHNOLOGIES</span><span><a href="/mentions-legales/">Mentions légales</a><a href="/confidentialite/">Confidentialité</a><a href="/cookies/">Cookies</a></span></div></div></footer>';

export async function onRequest(context){
  const requestUrl=new URL(context.request.url);
  if(requestUrl.pathname.startsWith('/admin')){
    const admin=await requireAdmin(context);
    if(!admin)return Response.redirect(new URL('/connexion/',requestUrl.origin),302);
  }
  const response=await context.next();
  const contentType=response.headers.get('content-type')||'';
  if(!contentType.includes('text/html'))return response;
  let html=await response.text(); const isAdmin=new URL(context.request.url).pathname.startsWith('/admin');
  if(!html.includes('/site-shell.css'))html=html.replace('</head>','<link rel="stylesheet" href="/site-shell.css?v=design-2"></head>');
  if(!html.includes('/api-client.js'))html=html.replace('</head>','<script src="/api-client.js" defer></script></head>');
  if(!html.includes('global-shell-header'))html=html.replace(/<body([^>]*)>/i,function(match,attributes){return '<body'+attributes+'>'+header});
  if(!html.includes('tamusni-rail'))html=html.replace(/<body([^>]*)>/i,function(match,attributes){return '<body'+attributes+'>'+(isAdmin?adminRail:rail)});
  if(!html.includes('global-shell-footer'))html=html.replace('</body>',footer+'</body>');
  if(!isAdmin&&!html.includes('/site-shell.js'))html=html.replace('</body>','<script src="/site-shell.js?v=roles-2" defer></script></body>');
  if(isAdmin&&!html.includes('/admin.css'))html=html.replace('</head>','<link rel="stylesheet" href="/admin.css"></head>');
  if(isAdmin&&!html.includes('/admin-app.js'))html=html.replace('</body>','<script src="/admin-app.js?v=roles-2" defer></script></body>');
  const headers=new Headers(response.headers);headers.delete('content-length');
  return new Response(html,{status:response.status,statusText:response.statusText,headers});
}
