const header='<header class="global-shell-header"><div class="global-shell-inner"><a class="global-shell-brand" href="/">TAMUSNI</a></div></header>';
const rail='<aside class="tamusni-rail" aria-label="Navigation TAMUSNI"><a class="rail-brand" href="/" aria-label="TAMUSNI — Retour à l’accueil" title="Retour à l’accueil">TAMUSNI</a><nav class="tamusni-rail-nav"><a class="rail-item" href="/intelligence-artificielle/" aria-label="Intelligence artificielle" data-label="Intelligence artificielle" title="Intelligence artificielle"><span class="rail-symbol" aria-hidden="true">AI</span></a><a class="rail-item" href="/innovation/" aria-label="Innovation" data-label="Innovation" title="Innovation"><span class="rail-symbol" aria-hidden="true">✦</span></a><a class="rail-item" href="/robotique/" aria-label="Robotique" data-label="Robotique" title="Robotique"><span class="rail-symbol" aria-hidden="true">⚙</span></a><a class="rail-item" href="/cybersecurite/" aria-label="Cybersécurité" data-label="Cybersécurité" title="Cybersécurité"><span class="rail-symbol" aria-hidden="true">◈</span></a><a class="rail-item" href="/espace/" aria-label="Espace" data-label="Espace" title="Espace"><span class="rail-symbol" aria-hidden="true">◇</span></a></nav><div class="tamusni-rail-tools"><select class="rail-language" id="global-language" aria-label="Langue" title="Langue"><option value="fr">FR</option><option value="ar">AR</option><option value="en">EN</option></select><button class="rail-item" id="rail-theme" type="button" aria-label="Changer de thème" data-label="Thème" title="Thème">◐</button><a class="rail-item rail-account rail-symbol" href="/connexion/" aria-label="Inscription et connexion" data-label="Inscription / Connexion" title="Inscription / Connexion">◎</a></div></aside>';
const footer='<footer class="global-shell-footer"><div class="global-footer-inner"><div class="global-footer-follow">Suivre TAMUSNI</div><div class="global-footer-social"><a href="#" aria-label="TAMUSNI sur X">X</a><a href="#" aria-label="TAMUSNI sur YouTube">YouTube</a><a href="#" aria-label="TAMUSNI sur Instagram">Instagram</a><a href="#" aria-label="TAMUSNI sur TikTok">TikTok</a><a href="#" aria-label="TAMUSNI sur Facebook">Facebook</a></div><div class="global-footer-bottom"><span>© 2026 TAMUSNI · A&amp;B TECHNOLOGIES</span><span><a href="/mentions-legales/">Mentions légales</a><a href="/confidentialite/">Confidentialité</a><a href="/cookies/">Cookies</a></span></div></div></footer>';

export async function onRequest(context){
  const response=await context.next();
  const contentType=response.headers.get('content-type')||'';
  if(!contentType.includes('text/html'))return response;
  let html=await response.text();
  if(!html.includes('/site-shell.css'))html=html.replace('</head>','<link rel="stylesheet" href="/site-shell.css"></head>');
  if(!html.includes('global-shell-header'))html=html.replace(/<body([^>]*)>/i,function(match,attributes){return '<body'+attributes+'>'+header});
  if(!html.includes('tamusni-rail'))html=html.replace(/<body([^>]*)>/i,function(match,attributes){return '<body'+attributes+'>'+rail});
  if(!html.includes('global-shell-footer'))html=html.replace('</body>',footer+'</body>');
  if(!html.includes('/site-shell.js'))html=html.replace('</body>','<script src="/site-shell.js" defer></script></body>');
  const headers=new Headers(response.headers);headers.delete('content-length');
  return new Response(html,{status:response.status,statusText:response.statusText,headers});
}
