import { json, readBody, requireSession, sameOrigin, validEmail } from "../_lib/auth.js";
import { createNewsletterIntent, subscribeUser } from "../_lib/newsletter-service.js";
import { normalizeNewsletterLocale } from "../_lib/newsletter-core.js";
import { consumeRateLimit, rateLimitResponse, turnstileError, verifyTurnstile } from "../_lib/account-security.js";

const messages={fr:{active:"Votre inscription à la revue hebdomadaire est active.",existing:"Cette adresse est déjà inscrite.",continue:"Connectez-vous ou créez votre compte pour confirmer l’inscription.",invalid:"Adresse e-mail invalide."},en:{active:"Your weekly review subscription is active.",existing:"This address is already subscribed.",continue:"Sign in or create your account to confirm the subscription.",invalid:"Invalid email address."},ar:{active:"تم تفعيل اشتراكك في النشرة الأسبوعية.",existing:"هذا العنوان مشترك بالفعل.",continue:"سجّل الدخول أو أنشئ حسابًا لتأكيد الاشتراك.",invalid:"عنوان البريد الإلكتروني غير صالح."},es:{active:"Tu suscripción a la revista semanal está activa.",existing:"Esta dirección ya está suscrita.",continue:"Accede o crea tu cuenta para confirmar la suscripción.",invalid:"Correo electrónico no válido."},pt:{active:"A sua subscrição da revista semanal está ativa.",existing:"Este endereço já está inscrito.",continue:"Entre ou crie a sua conta para confirmar a subscrição.",invalid:"Endereço de e-mail inválido."}};

export async function onRequestPost(context) {
  if (!sameOrigin(context.request)) return json({ error: "Origine refusée." }, 403);
  try { const body=await readBody(context.request);if(body.company)return json({ok:true},202);const locale=normalizeNewsletterLocale(body.locale);const copy=messages[locale];const session=await requireSession(context);
    if(session){const existing=await context.env.DB.prepare("SELECT status FROM newsletter_subscribers WHERE user_id=? OR lower(email)=lower(?)").bind(session.sub,session.email).first();if(existing?.status==='active')return json({ok:true,alreadySubscribed:true,message:copy.existing});const subscriber=await subscribeUser(context,session,locale,"homepage_account");return json({ok:true,subscriber:{status:subscriber.status,locale:subscriber.locale},message:copy.active},201)}
    const email=String(body.email||"").trim().toLowerCase();if(!validEmail(email))return json({error:copy.invalid},400);const limit=await consumeRateLimit(context,"newsletter",email);if(!limit.allowed)return rateLimitResponse(limit);if(context.env.TURNSTILE_SECRET_KEY){const turnstile=await verifyTurnstile(context,body.turnstileToken||body["cf-turnstile-response"]);if(!turnstile.success)return json({error:turnstileError(turnstile)},turnstile.unavailable?503:400)}const intent=await createNewsletterIntent(context,{email,locale});return json({ok:true,requiresAuth:true,redirect:intent.redirect,message:copy.continue},202,{"Set-Cookie":intent.cookie});
  } catch(error){if(error.message==="NEWSLETTER_RATE_LIMIT")return json({error:"Trop de demandes. Réessayez dans une heure."},429,{"Retry-After":"3600"});console.error("newsletter_subscription_failed",error);return json({error:"Inscription impossible pour le moment."},500)}
}
