(function(){
  function el(tag,text){var node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node}
  async function api(url,options){var response=await fetch(url,options);var data=await response.json().catch(function(){return{error:'Réponse invalide'}});if(response.status===401||response.status===403){location.href='/connexion/';throw new Error('Accès refusé')}if(!response.ok)throw new Error(data.error||'Opération impossible');return data}
  function request(method,body){return{method:method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}}
  document.querySelectorAll('[data-admin-tab]').forEach(function(button){button.onclick=function(){document.querySelectorAll('[data-admin-tab]').forEach(function(item){item.classList.toggle('is-active',item===button)});document.querySelectorAll('[data-admin-panel]').forEach(function(panel){panel.classList.toggle('is-active',panel.dataset.adminPanel===button.dataset.adminTab)})}});
  async function loadStats(){var data=await api('/api/admin/stats');var labels={users:'Utilisateurs',subscribers:'Newsletter',favorites:'Favoris',live:'En direct',content:'Contenus publiés',comments:'À modérer',reports:'Signalements',views:'Lectures'};var box=document.getElementById('stats');box.innerHTML='';Object.keys(labels).forEach(function(key){var card=el('article');card.className='stat';card.append(el('strong',data[key]||0),el('span',labels[key]));box.append(card)})}
  var contentForm=document.getElementById('content-form');
  function resetEditor(){contentForm.reset();contentForm.elements.id.value='';contentForm.elements.action.value='';contentForm.elements.authorName.value='Rédaction TAMUSNI';document.getElementById('editor-title').textContent='Créer un contenu';document.getElementById('cancel-edit').hidden=true}
  async function editContent(id){var data=await api('/api/admin/content?id='+encodeURIComponent(id));var item=data.item;var fields={id:item.id,action:'update',title:item.title,slug:item.slug,type:item.type,status:item.status,category:item.category,authorName:item.author_name,coverUrl:item.cover_url||'',scheduledAt:item.scheduled_at?item.scheduled_at.slice(0,16):'',excerpt:item.excerpt,summary:item.summary,body:item.body,mediaUrl:item.media_url||'',subtitlesUrl:item.subtitles_url||'',transcript:item.transcript||'',factCheckStatus:item.fact_check_status,tags:data.tags.map(function(tag){return tag.name}).join(', '),sourceLabel:data.sources[0]?data.sources[0].label:'',sourceUrl:data.sources[0]?data.sources[0].url:'',sourcePublisher:data.sources[0]?data.sources[0].publisher:'',sponsorName:item.sponsor_name||''};Object.keys(fields).forEach(function(key){if(contentForm.elements[key])contentForm.elements[key].value=fields[key]});contentForm.elements.sponsored.checked=Boolean(item.sponsored);document.getElementById('editor-title').textContent='Modifier le contenu';document.getElementById('cancel-edit').hidden=false;contentForm.scrollIntoView({behavior:'smooth'})}
  async function loadContent(){var data=await api('/api/admin/content');var box=document.getElementById('content-list');box.innerHTML='';data.items.forEach(function(item){var row=el('article');row.className='admin-row';var info=el('div');var link=el('a',item.title);link.href='/articles/'+item.slug;info.append(link,el('small',item.type+' · '+item.category+' · '+item.status));var controls=el('div');controls.className='row-controls';var edit=el('button','Modifier');edit.onclick=function(){editContent(item.id)};var select=el('select');['draft','review','scheduled','published','archived'].forEach(function(status){var option=el('option',status);option.value=status;option.selected=item.status===status;select.append(option)});select.onchange=async function(){try{await api('/api/admin/content',request('PATCH',{id:item.id,status:select.value}));loadStats()}catch(error){alert(error.message)}};var summarize=el('button','Résumé IA');summarize.onclick=async function(){summarize.disabled=true;try{await api('/api/admin/summarize',request('POST',{contentId:item.id}));summarize.textContent='Résumé créé'}catch(error){summarize.textContent='Erreur'}finally{summarize.disabled=false}};controls.append(edit,select,summarize);row.append(info,controls);box.append(row)})}
  async function loadComments(){var data=await api('/api/admin/comments');renderModeration(data.items,document.getElementById('comment-list'),'/api/admin/comments')}
  async function loadCommunity(){var data=await api('/api/admin/community');renderModeration(data.items,document.getElementById('community-list'),'/api/admin/community')}
  function renderModeration(items,box,url){box.innerHTML='';if(!items.length){box.append(el('p','Rien à modérer.'));return}items.forEach(function(item){var row=el('article');row.className='admin-row';var info=el('div');info.append(el('strong',(item.name||'Membre')+' — '+item.title),el('p',item.body),el('small',(item.kind==='topic'?'Nouveau sujet · ':'')+item.status));var controls=el('div');controls.className='row-controls';[['approved','Approuver'],['rejected','Refuser']].forEach(function(entry){var button=el('button',entry[1]);button.onclick=async function(){await api(url,request('PATCH',{id:item.id,status:entry[0],kind:item.kind}));row.remove();loadStats()};controls.append(button)});row.append(info,controls);box.append(row)})}
  async function loadUsers(){var data=await api('/api/admin/users');var box=document.getElementById('user-list');box.innerHTML='';data.items.forEach(function(item){var row=el('article');row.className='admin-row';var info=el('div');info.append(el('strong',item.name),el('small',item.email+' · '+item.created_at));var select=el('select');['USER','ADMIN'].forEach(function(role){var option=el('option',role);option.value=role;option.selected=item.role===role;select.append(option)});select.onchange=function(){api('/api/admin/users',request('PATCH',{id:item.id,role:select.value})).catch(function(error){alert(error.message)})};row.append(info,select);box.append(row)})}
  async function loadAds(){var data=await api('/api/admin/ads');var box=document.getElementById('ad-list');box.innerHTML='';if(!data.items.length)box.append(el('p','Aucune campagne.'));var types={display:'Bannière',native:'Native',sponsored:'Sponsorisé',affiliate:'Affiliation',house:'Autopromotion'};data.items.forEach(function(item){var row=el('article');row.className='admin-row';var info=el('div');info.append(el('strong',item.name+' — '+item.headline),el('small',(types[item.ad_type]||item.ad_type)+' · '+item.placement+' · '+item.status+' · '+item.impressions+' impressions · '+item.clicks+' clics'));var select=el('select');['draft','active','paused','ended'].forEach(function(status){var option=el('option',status);option.value=status;option.selected=item.status===status;select.append(option)});select.onchange=async function(){await api('/api/admin/ads',request('PATCH',{id:item.id,status:select.value}));loadAds()};row.append(info,select);box.append(row)})}
  async function loadPolls(){var data=await api('/api/admin/polls');var box=document.getElementById('poll-list');box.innerHTML='';data.items.forEach(function(item){var row=el('article');row.className='admin-row';var info=el('div');info.append(el('strong',item.question),el('small',(item.votes||0)+' vote(s) · '+(item.active?'Actif':'Fermé')));var button=el('button',item.active?'Fermer':'Réactiver');button.onclick=async function(){await api('/api/admin/polls',request('PATCH',{id:item.id,active:!item.active}));loadPolls()};row.append(info,button);box.append(row)})}
  contentForm.onsubmit=async function(event){event.preventDefault();var payload={};new FormData(contentForm).forEach(function(value,key){payload[key]=value});payload.sponsored=contentForm.elements.sponsored.checked;var method=payload.action==='update'?'PATCH':'POST';try{await api('/api/admin/content',request(method,payload));document.getElementById('editor-message').textContent=method==='PATCH'?'Contenu mis à jour et révision enregistrée.':'Contenu enregistré.';resetEditor();await Promise.all([loadContent(),loadStats()])}catch(error){document.getElementById('editor-message').textContent=error.message}};
  document.getElementById('cancel-edit').onclick=resetEditor;
  document.getElementById('ad-form').onsubmit=async function(event){event.preventDefault();var form=event.currentTarget,payload={};new FormData(form).forEach(function(value,key){payload[key]=value});try{await api('/api/admin/ads',request('POST',payload));form.reset();document.getElementById('ad-message').textContent='Campagne créée.';loadAds()}catch(error){document.getElementById('ad-message').textContent=error.message}};
  document.getElementById('poll-form').onsubmit=async function(event){event.preventDefault();var form=event.currentTarget,payload={};new FormData(form).forEach(function(value,key){payload[key]=value});try{await api('/api/admin/polls',request('POST',payload));form.reset();document.getElementById('poll-message').textContent='Sondage publié.';loadPolls()}catch(error){document.getElementById('poll-message').textContent=error.message}};
  document.getElementById('logout').onclick=async function(){await fetch('/api/auth/logout',{method:'POST'});location.href='/'};
  Promise.all([loadStats(),loadContent(),loadComments(),loadCommunity(),loadUsers(),loadAds(),loadPolls()]).then(function(){document.getElementById('admin-message').textContent='Administration reliée à la base de production.'}).catch(function(error){document.getElementById('admin-message').textContent=error.message});
})();
