(function(){
  var body=document.body;var contentId=body.dataset.contentId;var slug=body.dataset.contentSlug;var progressSent=0;
  function sendProgress(force){var height=document.documentElement.scrollHeight-innerHeight;var progress=height>0?Math.round(scrollY/height*100):100;if(!force&&progress-progressSent<10)return;progressSent=progress;fetch('/api/content/'+encodeURIComponent(slug),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({progress:progress}),keepalive:true}).catch(function(){})}
  sendProgress(true);addEventListener('scroll',function(){sendProgress(false)},{passive:true});
  document.querySelectorAll('[data-timeline-event]').forEach(function(button){button.onclick=function(){document.querySelectorAll('[data-timeline-event]').forEach(function(item){item.classList.remove('is-active')});button.classList.add('is-active')}});
  document.getElementById('reader-mode').onclick=function(){body.classList.toggle('reader-focus')};
  document.getElementById('text-size').onclick=function(){body.classList.toggle('text-large')};
  document.getElementById('copy-link').onclick=async function(){await navigator.clipboard.writeText(location.href);this.textContent='Lien copié'};
  document.getElementById('listen').onclick=function(){if(speechSynthesis.speaking){speechSynthesis.cancel();this.textContent='Écouter l’article';return}var speech=new SpeechSynthesisUtterance(document.querySelector('h1').textContent+'. '+document.getElementById('article-body').textContent);speech.lang=document.documentElement.lang||'fr';speechSynthesis.speak(speech);this.textContent='Arrêter la lecture'};
  document.getElementById('save-item').onclick=async function(){var response=await fetch('/api/favorites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemId:contentId,itemType:body.dataset.contentType==='video'?'video':'article',title:document.querySelector('h1').textContent,url:location.pathname})});this.textContent=response.ok?'Enregistré':'Connexion requise';if(response.status===401)location.href='/connexion/?next='+encodeURIComponent(location.pathname)};
  document.querySelectorAll('[data-reaction]').forEach(function(button){button.onclick=async function(){var response=await fetch('/api/reactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contentId:contentId,reaction:button.dataset.reaction})});if(response.status===401){location.href='/connexion/?next='+encodeURIComponent(location.pathname);return}if(response.ok){document.querySelectorAll('[data-reaction]').forEach(function(item){item.disabled=false});button.disabled=true}}});
  var form=document.getElementById('comment-form');form.onsubmit=async function(event){event.preventDefault();var textarea=form.querySelector('textarea');var response=await fetch('/api/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contentId:contentId,body:textarea.value})});var data=await response.json();document.getElementById('comment-message').textContent=data.message||data.error;if(response.ok)textarea.value='';if(response.status===401)location.href='/connexion/?next='+encodeURIComponent(location.pathname)};
  document.getElementById('report-content').onclick=async function(){var reason=prompt('Motif du signalement');if(!reason)return;var response=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetType:'content',targetId:contentId,reason:reason})});this.textContent=response.ok?'Signalement envoyé':'Connexion requise'};
})();
