(function(){
  var engagementStyle=document.createElement('link');engagementStyle.rel='stylesheet';engagementStyle.href='/engagement.css';document.head.appendChild(engagementStyle);
  var body=document.body;var contentId=body.dataset.contentId;var slug=body.dataset.contentSlug;var progressSent=0;
  var actions=document.createElement('div');actions.className='content-actions';actions.setAttribute('aria-label','Popularité et partage');actions.innerHTML='<button id="like-button" type="button" aria-pressed="false">♥ <span>J’aime</span> <strong id="like-count">0</strong></button><button id="share-button" type="button">↗ <span>Partager</span></button><p aria-label="Nombre de vues">◉ <strong id="view-count">0</strong> vues</p><span id="share-status" class="visually-hidden" role="status"></span>';var meta=document.querySelector('.meta');if(meta)meta.insertAdjacentElement('afterend',actions);
  function renderMetrics(data){if(!data)return;var views=document.getElementById('view-count'),likes=document.getElementById('like-count'),likeButton=document.getElementById('like-button');if(views&&Number.isFinite(Number(data.views)))views.textContent=Number(data.views).toLocaleString(document.documentElement.lang||'fr');if(likes&&Number.isFinite(Number(data.likes)))likes.textContent=Number(data.likes).toLocaleString(document.documentElement.lang||'fr');if(likeButton){likeButton.setAttribute('aria-pressed',data.liked?'true':'false');likeButton.classList.toggle('is-liked',Boolean(data.liked))}}
  function sendProgress(force){var height=document.documentElement.scrollHeight-innerHeight;var progress=height>0?Math.round(scrollY/height*100):100;if(!force&&progress-progressSent<10)return;progressSent=progress;fetch('/api/content/'+encodeURIComponent(slug),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:force?'view':'progress',progress:progress}),keepalive:true}).then(function(response){return response.ok?response.json():null}).then(renderMetrics).catch(function(){})}
  sendProgress(true);addEventListener('scroll',function(){sendProgress(false)},{passive:true});
  document.querySelectorAll('[data-timeline-event]').forEach(function(button){button.onclick=function(){document.querySelectorAll('[data-timeline-event]').forEach(function(item){item.classList.remove('is-active')});button.classList.add('is-active')}});
  document.getElementById('reader-mode').onclick=function(){body.classList.toggle('reader-focus')};
  document.getElementById('text-size').onclick=function(){body.classList.toggle('text-large')};
  document.getElementById('copy-link').onclick=async function(){await navigator.clipboard.writeText(location.href);this.textContent='Lien copié'};
  document.getElementById('like-button').onclick=async function(){var button=this;button.disabled=true;try{var response=await fetch('/api/content/'+encodeURIComponent(slug),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'like'})});if(response.ok)renderMetrics(await response.json())}finally{button.disabled=false}};
  document.getElementById('share-button').onclick=async function(){var status=document.getElementById('share-status');try{if(navigator.share){await navigator.share({title:document.querySelector('h1').textContent,text:document.querySelector('.lead').textContent,url:location.href});status.textContent='Contenu partagé'}else{await navigator.clipboard.writeText(location.href);status.textContent='Lien copié';this.querySelector('span').textContent='Lien copié'}}catch(error){if(error&&error.name!=='AbortError')status.textContent='Partage indisponible'}};
  document.getElementById('listen').onclick=function(){if(speechSynthesis.speaking){speechSynthesis.cancel();this.textContent='Écouter l’article';return}var speech=new SpeechSynthesisUtterance(document.querySelector('h1').textContent+'. '+document.getElementById('article-body').textContent);speech.lang=document.documentElement.lang||'fr';speechSynthesis.speak(speech);this.textContent='Arrêter la lecture'};
  document.getElementById('save-item').onclick=async function(){var response=await fetch('/api/favorites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemId:contentId,itemType:body.dataset.contentType==='video'?'video':'article',title:document.querySelector('h1').textContent,url:location.pathname})});this.textContent=response.ok?'Enregistré':'Connexion requise';if(response.status===401)location.href='/connexion/?next='+encodeURIComponent(location.pathname)};
  document.querySelectorAll('[data-reaction]').forEach(function(button){button.onclick=async function(){var response=await fetch('/api/reactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contentId:contentId,reaction:button.dataset.reaction})});if(response.status===401){location.href='/connexion/?next='+encodeURIComponent(location.pathname);return}if(response.ok){document.querySelectorAll('[data-reaction]').forEach(function(item){item.disabled=false});button.disabled=true}}});
  var form=document.getElementById('comment-form');form.onsubmit=async function(event){event.preventDefault();var textarea=form.querySelector('textarea');var response=await fetch('/api/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contentId:contentId,body:textarea.value})});var data=await response.json();document.getElementById('comment-message').textContent=data.message||data.error;if(response.ok)textarea.value='';if(response.status===401)location.href='/connexion/?next='+encodeURIComponent(location.pathname)};
  document.getElementById('report-content').onclick=async function(){var reason=prompt('Motif du signalement');if(!reason)return;var response=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetType:'content',targetId:contentId,reason:reason})});this.textContent=response.ok?'Signalement envoyé':'Connexion requise'};
})();
