(function(){
  const root=document.getElementById('contributor-app');if(!root)return;
  const copy={
    fr:{kicker:'Espace contributeur',title:'Vos idées, notre prochaine lecture.',intro:'Préparez des articles et des brèves sourcés. Chaque proposition est examinée par la rédaction avant publication.',create:'Nouvelle proposition',mine:'Mes contenus',how:'Comment ça marche',rules:'Seuls les articles et les brèves sont acceptés. Ajoutez une image et au moins une source HTTPS. Après l’envoi, votre proposition est verrouillée, même si elle est refusée.',type:'Format',article:'Article',brief:'Brève',category:'Rubrique',titleLabel:'Titre',excerpt:'Chapô / résumé',body:'Texte',bodyHint:'Texte brut, paragraphes séparés par des lignes vides. Minimum à l’envoi : 900 caractères pour un article et 250 pour une brève.',image:'Image principale (JPEG)',imageHint:'JPEG uniquement, jusqu’à 1,4 Mo. L’image est hébergée par TAMUSNI.',source:'Source',sourceName:'Nom de la source',url:'Lien HTTPS',publisher:'Organisme / média',note:'Note (facultative)',addSource:'Ajouter une source',save:'Enregistrer le brouillon',preview:'Prévisualiser',send:'Envoyer à validation',back:'Retour',empty:'Aucun contenu pour le moment.',statusDraft:'Brouillon',statusSubmitted:'Envoyé',statusApproved:'Validé / publié',statusRejected:'Refusé',created:'Créé le',submitted:'Envoyé le',reviewed:'Examiné le',reason:'Motif du refus',open:'Ouvrir',edit:'Modifier le brouillon',delete:'Supprimer le brouillon',confirm:'Après envoi, vous ne pourrez plus modifier cette proposition, même si elle est refusée. Voulez-vous continuer ?',confirmDelete:'Supprimer définitivement ce brouillon ?',saved:'Brouillon enregistré.',sent:'Proposition envoyée à la rédaction.',required:'Complétez le titre, le type et la rubrique avant de sauvegarder.',uploading:'Import de l’image…',imageReady:'Image prête',working:'En cours…',public:'Voir l’article publié',logout:'Se reconnecter',sourceRequired:'Ajoutez une source avec un nom et un lien HTTPS.'},
    en:{kicker:'Contributor space',title:'Your ideas, our next story.',intro:'Prepare sourced articles and briefs. Every submission is reviewed by the editorial team before publication.',create:'New submission',mine:'My submissions',how:'How it works',rules:'Only articles and briefs are accepted. Add an image and at least one HTTPS source. Once submitted, your proposal is locked, even if rejected.',type:'Format',article:'Article',brief:'Brief',category:'Section',titleLabel:'Title',excerpt:'Standfirst / summary',body:'Text',bodyHint:'Plain text, with paragraphs separated by blank lines. Minimum on submission: 900 characters for an article and 250 for a brief.',image:'Main image (JPEG)',imageHint:'JPEG only, up to 1.4 MB. Image hosted by TAMUSNI.',source:'Source',sourceName:'Source name',url:'HTTPS link',publisher:'Organization / publisher',note:'Note (optional)',addSource:'Add a source',save:'Save draft',preview:'Preview',send:'Submit for review',back:'Back',empty:'No submissions yet.',statusDraft:'Draft',statusSubmitted:'Submitted',statusApproved:'Approved / published',statusRejected:'Rejected',created:'Created',submitted:'Submitted',reviewed:'Reviewed',reason:'Reason for rejection',open:'Open',edit:'Edit draft',delete:'Delete draft',confirm:'After submission, you cannot edit this proposal, even if it is rejected. Continue?',confirmDelete:'Permanently delete this draft?',saved:'Draft saved.',sent:'Submission sent to the editorial team.',required:'Enter a title, format and section before saving.',uploading:'Uploading image…',imageReady:'Image ready',working:'Working…',sourceRequired:'Add a source name and HTTPS link.'},
    ar:{kicker:'مساحة المساهم',title:'أفكارك، موضوعنا القادم.',intro:'أعدّ مقالات وموجزات موثقة. يراجع فريق التحرير كل مقترح قبل النشر.',create:'مقترح جديد',mine:'مساهماتي',how:'كيف يعمل',rules:'نقبل المقالات والموجزات فقط. أضف صورة ومصدراً واحداً على الأقل عبر HTTPS. بعد الإرسال يُقفل المقترح حتى عند رفضه.',type:'الصيغة',article:'مقال',brief:'موجز',category:'القسم',titleLabel:'العنوان',excerpt:'المقدمة / الملخص',body:'النص',bodyHint:'نص عادي، افصل الفقرات بسطر فارغ. الحد الأدنى: 900 حرف للمقال و250 للموجز.',image:'الصورة الرئيسية (JPEG)',imageHint:'JPEG فقط، حتى 1.4 ميغابايت. تستضاف الصورة لدى TAMUSNI.',source:'المصدر',sourceName:'اسم المصدر',url:'رابط HTTPS',publisher:'الجهة / الناشر',note:'ملاحظة (اختيارية)',addSource:'إضافة مصدر',save:'حفظ المسودة',preview:'معاينة',send:'إرسال للمراجعة',back:'رجوع',empty:'لا توجد مساهمات بعد.',statusDraft:'مسودة',statusSubmitted:'مرسل',statusApproved:'مقبول / منشور',statusRejected:'مرفوض',created:'أُنشئ في',submitted:'أُرسل في',reviewed:'رُوجع في',reason:'سبب الرفض',open:'فتح',edit:'تعديل المسودة',delete:'حذف المسودة',confirm:'بعد الإرسال لن تتمكن من تعديل هذا المقترح حتى إذا رُفض. هل تريد المتابعة؟',confirmDelete:'حذف هذه المسودة نهائياً؟',saved:'حُفظت المسودة.',sent:'أُرسل المقترح إلى فريق التحرير.',required:'أدخل العنوان والصيغة والقسم قبل الحفظ.',uploading:'جارٍ رفع الصورة…',imageReady:'الصورة جاهزة',working:'جارٍ التنفيذ…',sourceRequired:'أضف اسم المصدر ورابط HTTPS.'},
    es:{kicker:'Espacio de colaboradores',title:'Tus ideas, nuestra próxima historia.',intro:'Prepara artículos y breves con fuentes. El equipo editorial revisa cada propuesta antes de publicarla.',create:'Nueva propuesta',mine:'Mis contenidos',how:'Cómo funciona',rules:'Solo se aceptan artículos y breves. Añade una imagen y al menos una fuente HTTPS. Tras enviarla, la propuesta queda bloqueada incluso si se rechaza.',type:'Formato',article:'Artículo',brief:'Breve',category:'Sección',titleLabel:'Título',excerpt:'Entradilla / resumen',body:'Texto',bodyHint:'Texto sin formato; separa los párrafos con líneas en blanco. Mínimo: 900 caracteres para un artículo y 250 para una breve.',image:'Imagen principal (JPEG)',imageHint:'Solo JPEG, hasta 1,4 MB. Imagen alojada por TAMUSNI.',source:'Fuente',sourceName:'Nombre de la fuente',url:'Enlace HTTPS',publisher:'Organización / medio',note:'Nota (opcional)',addSource:'Añadir fuente',save:'Guardar borrador',preview:'Vista previa',send:'Enviar a revisión',back:'Volver',empty:'Todavía no hay contenidos.',statusDraft:'Borrador',statusSubmitted:'Enviado',statusApproved:'Aprobado / publicado',statusRejected:'Rechazado',created:'Creado',submitted:'Enviado',reviewed:'Revisado',reason:'Motivo del rechazo',open:'Abrir',edit:'Editar borrador',delete:'Eliminar borrador',confirm:'Después del envío no podrás editar la propuesta, aunque se rechace. ¿Continuar?',confirmDelete:'¿Eliminar definitivamente este borrador?',saved:'Borrador guardado.',sent:'Propuesta enviada al equipo editorial.',required:'Completa el título, el formato y la sección antes de guardar.',uploading:'Subiendo imagen…',imageReady:'Imagen lista',working:'Procesando…',sourceRequired:'Añade el nombre de la fuente y un enlace HTTPS.'},
    pt:{kicker:'Espaço do colaborador',title:'As suas ideias, a nossa próxima leitura.',intro:'Prepare artigos e notas com fontes. A equipa editorial revê cada proposta antes da publicação.',create:'Nova proposta',mine:'Os meus conteúdos',how:'Como funciona',rules:'Só são aceites artigos e notas. Adicione uma imagem e pelo menos uma fonte HTTPS. Após o envio, a proposta fica bloqueada mesmo se for recusada.',type:'Formato',article:'Artigo',brief:'Nota',category:'Secção',titleLabel:'Título',excerpt:'Abertura / resumo',body:'Texto',bodyHint:'Texto simples; separe os parágrafos com linhas em branco. Mínimo: 900 caracteres para artigo e 250 para nota.',image:'Imagem principal (JPEG)',imageHint:'Apenas JPEG, até 1,4 MB. Imagem alojada pela TAMUSNI.',source:'Fonte',sourceName:'Nome da fonte',url:'Ligação HTTPS',publisher:'Organização / meio',note:'Nota (opcional)',addSource:'Adicionar fonte',save:'Guardar rascunho',preview:'Pré-visualizar',send:'Enviar para revisão',back:'Voltar',empty:'Ainda não há conteúdos.',statusDraft:'Rascunho',statusSubmitted:'Enviado',statusApproved:'Aprovado / publicado',statusRejected:'Recusado',created:'Criado',submitted:'Enviado',reviewed:'Revisto',reason:'Motivo da recusa',open:'Abrir',edit:'Editar rascunho',delete:'Eliminar rascunho',confirm:'Após o envio, não poderá editar esta proposta, mesmo se for recusada. Continuar?',confirmDelete:'Eliminar definitivamente este rascunho?',saved:'Rascunho guardado.',sent:'Proposta enviada à equipa editorial.',required:'Preencha o título, o formato e a secção antes de guardar.',uploading:'A carregar imagem…',imageReady:'Imagem pronta',working:'A processar…',sourceRequired:'Adicione o nome da fonte e uma ligação HTTPS.'}
  };
  copy.en.edit='Edit draft';copy.ar.edit='تعديل المسودة';copy.es.edit='Editar borrador';copy.pt.edit='Editar rascunho';
  Object.assign(copy.en,{public:'View published story',logout:'Sign in again'});Object.assign(copy.ar,{public:'عرض المقال المنشور',logout:'تسجيل الدخول من جديد'});Object.assign(copy.es,{public:'Ver el artículo publicado',logout:'Volver a acceder'});Object.assign(copy.pt,{public:'Ver o artigo publicado',logout:'Entrar novamente'});
  copy.fr.bodyHint='Texte brut, paragraphes séparés par des lignes vides. Minimum : chapô de 60 caractères, article de 900 caractères ou brève de 250 caractères.';
  copy.en.bodyHint='Plain text, paragraphs separated by blank lines. Minimum: 60-character standfirst, 900-character article or 250-character brief.';
  copy.ar.bodyHint='نص عادي، افصل الفقرات بسطر فارغ. الحد الأدنى: مقدمة من 60 حرفاً، ومقال من 900 حرف أو موجز من 250 حرفاً.';
  copy.es.bodyHint='Texto sin formato, párrafos separados por líneas en blanco. Mínimo: entradilla de 60 caracteres, artículo de 900 o breve de 250.';
  copy.pt.bodyHint='Texto simples, parágrafos separados por linhas vazias. Mínimo: abertura de 60 caracteres, artigo de 900 ou nota de 250.';
  const topics=['Intelligence artificielle','Innovation','Robotique','Cybersécurité','Espace'];
  const translatedTopics={fr:topics,en:['Artificial intelligence','Innovation','Robotics','Cybersecurity','Space'],ar:['الذكاء الاصطناعي','الابتكار','الروبوتات','الأمن السيبراني','الفضاء'],es:['Inteligencia artificial','Innovación','Robótica','Ciberseguridad','Espacio'],pt:['Inteligência artificial','Inovação','Robótica','Cibersegurança','Espaço']};
  let locale=copy[document.body.dataset.locale]?document.body.dataset.locale:'fr',items=[],editing=null,coverUrl='',sources=[{}],notice='';
  const t=k=>copy[locale]?.[k]||copy.fr[k]||k,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date=s=>s?new Intl.DateTimeFormat(locale,{dateStyle:'medium'}).format(new Date(s)):'—';
  async function api(path,options){const response=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options?.headers||{})},...options});const data=await response.json().catch(()=>({}));if(!response.ok){if(response.status===401)location.href='/connexion/';throw new Error(data.error||'Request failed')}return data}
  function setNotice(text,error=false){notice=text;const node=root.querySelector('[data-notice]');if(node){node.textContent=text;node.dataset.error=error?'true':'false'}}
  function preserveEditor(){if(root.querySelector('#submission-form'))editing={...(editing||{}),...getForm()}}
  function localizeTopics(){root.querySelectorAll('#category option').forEach((option,index)=>{option.value=topics[index];option.textContent=translatedTopics[locale][index]||topics[index]});root.querySelectorAll('.contrib-meta').forEach(meta=>{const category=meta.querySelector('span:nth-child(2)');if(category){const index=topics.indexOf(category.textContent);if(index>=0)category.textContent=translatedTopics[locale][index]}})}
  function render(){document.documentElement.lang=locale;document.documentElement.dir=locale==='ar'?'rtl':'ltr';const view=location.hash.slice(1)||'overview';const shown=view==='drafts'?items.filter(item=>item.status==='draft'):view==='submitted'?items.filter(item=>item.status!=='draft'):items;document.querySelectorAll('[data-contributor-view]').forEach(button=>button.setAttribute('aria-current',button.dataset.contributorView===view?'page':'false'));root.innerHTML=`<header class="contrib-top reveal is-visible"><div><p class="contrib-kicker">${t('kicker')}</p><h1>${t('title')}</h1><p>${t('intro')}</p></div><button class="contrib-button primary" data-create>＋ ${t('create')}</button></header><div class="contrib-layout"><section class="contrib-panel"><h2>${t('mine')}</h2><div aria-live="polite">${notice?`<p class="contrib-alert" data-notice>${esc(notice)}</p>`:''}</div><div>${shown.length?shown.map(item=>`<article class="contrib-entry"><div><span class="contrib-status">${esc(t('status'+item.status[0].toUpperCase()+item.status.slice(1)))}</span><h3>${esc(item.title||t('statusDraft'))}</h3><div class="contrib-meta"><span>${esc(item.type==='article'?t('article'):t('brief'))}</span><span>${esc(item.category)}</span><span>${t('created')} ${date(item.created_at)}</span>${item.submitted_at?`<span>${t('submitted')} ${date(item.submitted_at)}</span>`:''}${item.reviewed_at?`<span>${t('reviewed')} ${date(item.reviewed_at)}</span>`:''}</div></div><div class="contrib-row-actions">${item.status==='draft'?`<button class="contrib-button" data-edit="${esc(item.id)}">${t('edit')}</button><button class="contrib-button danger" data-delete="${esc(item.id)}">${t('delete')}</button>`:''}${item.status==='approved'&&item.published_content_id?`<a class="contrib-button" href="/${locale}/articles/${esc(item.published_slug)}/">${t('public')}</a>`:''}</div>${item.review_reason?`<div class="contrib-reason"><strong>${t('reason')} :</strong> ${esc(item.review_reason)}</div>`:''}</article>`).join(''):`<p class="contrib-empty">${t('empty')}</p>`}</div></section><aside class="contrib-panel card"><h2>${t('how')}</h2><p>${t('rules')}</p></aside></div>`;localizeTopics();root.querySelector('[data-create]').onclick=()=>openEditor();root.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>loadEditor(button.dataset.edit));root.querySelectorAll('[data-delete]').forEach(button=>button.onclick=()=>deleteDraft(button.dataset.delete))}
  async function refresh(){root.setAttribute('aria-busy','true');try{items=(await api('/api/contributor/submissions')).items||[];render()}catch(error){root.innerHTML=`<section class="contrib-panel"><h1>${esc(error.message)}</h1><a href="/${locale}/connexion/">${t('logout')}</a></section>`}finally{root.setAttribute('aria-busy','false');document.body.classList.add('role-ready')}}
  function sourceFields(){return sources.map((source,index)=>`<fieldset class="contrib-source"><legend>${t('source')} ${index+1}</legend><div class="contrib-field"><label for="source-name-${index}">${t('sourceName')}</label><input id="source-name-${index}" data-source="label" data-index="${index}" value="${esc(source.label)}" required></div><div class="contrib-field"><label for="source-url-${index}">${t('url')}</label><input id="source-url-${index}" data-source="url" data-index="${index}" type="url" inputmode="url" placeholder="https://…" value="${esc(source.url)}" required></div><div class="contrib-field"><label for="source-pub-${index}">${t('publisher')}</label><input id="source-pub-${index}" data-source="publisher" data-index="${index}" value="${esc(source.publisher)}"></div><div class="contrib-field"><label for="source-note-${index}">${t('note')}</label><input id="source-note-${index}" data-source="note" data-index="${index}" value="${esc(source.note)}"></div>${sources.length>1?`<button class="contrib-button danger" type="button" data-remove-source="${index}">${t('delete')}</button>`:''}</fieldset>`).join('')}
  function editor(){const item=editing||{};root.innerHTML=`<header class="contrib-top"><div><p class="contrib-kicker">${t('kicker')}</p><h1>${item.id?t('edit'):t('create')}</h1></div><button class="contrib-button" data-back>${t('back')}</button></header><form id="submission-form" novalidate><div class="contrib-layout"><section class="contrib-panel card"><div class="contrib-field"><label for="type">${t('type')}</label><select id="type" name="type"><option value="article" ${item.type!=='brief'?'selected':''}>${t('article')}</option><option value="brief" ${item.type==='brief'?'selected':''}>${t('brief')}</option></select></div><div class="contrib-field"><label for="category">${t('category')}</label><select id="category" name="category">${topics.map(topic=>`<option value="${esc(topic)}" ${topic===item.category?'selected':''}>${esc(topic)}</option>`).join('')}</select></div><div class="contrib-field"><label for="title">${t('titleLabel')}</label><input id="title" name="title" required maxlength="240" value="${esc(item.title)}"></div><div class="contrib-field"><label for="excerpt">${t('excerpt')}</label><textarea id="excerpt" name="excerpt" maxlength="600">${esc(item.excerpt)}</textarea></div><div class="contrib-field"><label for="body">${t('body')}</label><textarea id="body" name="body" required>${esc(item.body)}</textarea></div><p class="contrib-help">${t('bodyHint')}</p><div class="contrib-field"><label for="image">${t('image')}</label><input id="image" type="file" accept="image/jpeg,image/png,image/webp"><span class="contrib-help">${t('imageHint')}</span><div data-image-preview>${coverUrl?`<img class="contrib-image" src="${esc(coverUrl)}" alt="${t('image')}"><span>${t('imageReady')}</span>`:''}</div></div><h2>${t('source')}</h2><div class="contrib-sources">${sourceFields()}</div><button class="contrib-button" type="button" data-add-source>＋ ${t('addSource')}</button><p class="contrib-alert" data-notice aria-live="polite">${esc(notice)}</p><div class="contrib-actions"><button class="contrib-button primary" type="button" data-save>${t('save')}</button><button class="contrib-button" type="button" data-preview>${t('preview')}</button><button class="contrib-button primary" type="button" data-submit>${t('send')}</button></div></section><aside class="contrib-panel card"><h2>${t('how')}</h2><p>${t('rules')}</p></aside></div></form>`;
    localizeTopics();
    root.querySelector('[data-back]').onclick=()=>{editing=null;coverUrl='';sources=[{}];refresh()};
    root.querySelector('[data-add-source]').onclick=()=>{readSources();sources.push({});editor()};
    root.querySelectorAll('[data-remove-source]').forEach(button=>button.onclick=()=>{readSources();sources.splice(Number(button.dataset.removeSource),1);editor()});
    root.querySelector('[data-image-preview]').innerHTML=coverUrl?`<img class="contrib-image" src="${esc(coverUrl)}" alt="${t('image')}"><span>${t('imageReady')}</span>`:'';
    root.querySelector('#image').onchange=uploadImage;
    root.querySelector('[data-save]').onclick=()=>save('draft');root.querySelector('[data-submit]').onclick=()=>{if(!confirm(t('confirm')))return;save('submit')};root.querySelector('[data-preview]').onclick=preview;
    root.querySelectorAll('[data-source]').forEach(input=>input.oninput=()=>{sources[Number(input.dataset.index)][input.dataset.source]=input.value});
  }
  function readSources(){root.querySelectorAll('[data-source]').forEach(input=>sources[Number(input.dataset.index)][input.dataset.source]=input.value)}
  async function uploadImage(event){const file=event.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setNotice(t('imageHint'),true);return}setNotice(t('uploading'));try{const data=await new Promise((resolve,reject)=>{const image=new Image(),reader=new FileReader();reader.onerror=reject;reader.onload=()=>image.src=reader.result;image.onerror=reject;image.onload=()=>{const scale=Math.min(1,1600/image.width,1600/image.height),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);let output=canvas.toDataURL('image/jpeg',.84),quality=.74;while(output.length>1_850_000&&quality>=.44){output=canvas.toDataURL('image/jpeg',quality);quality-=.1}resolve(output)};reader.readAsDataURL(file)});const result=await api('/api/contributor/upload',{method:'POST',body:JSON.stringify({data})});coverUrl=result.url;root.querySelector('[data-image-preview]').innerHTML=`<img class="contrib-image" src="${esc(coverUrl)}" alt="${t('image')}"><span>${t('imageReady')}</span>`;setNotice('')}catch(error){setNotice(error.message,true)}}
  function getForm(){const form=root.querySelector('#submission-form');return {id:editing?.id,type:form.type.value,category:form.category.value,title:form.title.value,excerpt:form.excerpt.value,body:form.body.value,coverUrl,sources:(readSources(),sources)}}
  async function save(action){const payload=getForm();if(!payload.title.trim()||!payload.type||!payload.category){setNotice(t('required'),true);return}if(action==='submit'&&(!payload.coverUrl||!payload.sources.some(source=>source.label&&/^https:\/\//i.test(source.url||'')))){setNotice(t('sourceRequired'),true);return}try{setNotice(t('working'));const result=await api('/api/contributor/submissions',{method:'POST',body:JSON.stringify({...payload,action})});if(action==='submit'){editing=null;coverUrl='';sources=[{}];notice=t('sent');await refresh()}else{editing={...editing,id:result.id};notice=t('saved');await refresh();await loadEditor(result.id)}}catch(error){setNotice(error.message,true)}}
  function preview(){readSources();const data=getForm(),d=document.createElement('dialog');d.className='contrib-preview';d.setAttribute('aria-labelledby','preview-title');d.innerHTML=`<button class="contrib-button" data-close>${t('back')}</button><p class="contrib-kicker">${esc(data.category)} · ${esc(data.type==='article'?t('article'):t('brief'))}</p><h2 id="preview-title">${esc(data.title||t('titleLabel'))}</h2><p>${esc(data.excerpt)}</p>${coverUrl?`<img class="contrib-image" src="${esc(coverUrl)}" alt="${t('image')}">`:''}<div class="contrib-preview-body">${esc(data.body)}</div><h3>${t('source')}</h3>${data.sources.map(s=>`<p><a href="${esc(s.url)}" rel="noopener noreferrer" target="_blank">${esc(s.label)}</a></p>`).join('')}<button class="contrib-button" data-close>${t('back')}</button>`;document.body.append(d);d.showModal();d.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>d.close());d.addEventListener('close',()=>d.remove(),{once:true})}
  async function loadEditor(id){try{const result=await api(`/api/contributor/submissions?id=${encodeURIComponent(id)}`);editing=result.item;coverUrl=result.item.cover_url||'';sources=result.sources.length?result.sources.map(source=>({...source})): [{}];notice='';editor()}catch(error){notice=error.message;refresh()}}
  async function openEditor(){editing=null;coverUrl='';sources=[{}];notice='';editor()}
  async function deleteDraft(id){if(!confirm(t('confirmDelete')))return;try{await api('/api/contributor/submissions',{method:'POST',body:JSON.stringify({id,action:'delete'})});await refresh()}catch(error){setNotice(error.message,true)}}
  document.querySelectorAll('[data-contributor-view]').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.contributorView==='create')openEditor();else{location.hash=button.dataset.contributorView;render()}}));
  window.addEventListener('hashchange',()=>{if(!document.querySelector('#submission-form'))render()});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',refresh,{once:true});else refresh();
})();
