(() => {
  const root = document.documentElement;
  const locale = document.body.dataset.locale || 'fr';
  document.querySelectorAll('input[type="password"][minlength="12"]').forEach(input=>input.setAttribute('minlength','6'));
  const text = {
    fr:{working:'Traitement…',done:'Demande enregistrée.',error:'Une erreur est survenue.',confirm:'Supprimer définitivement ce compte ?',copied:'Lien copié.',login:'Connectez-vous pour enregistrer cet article.',pause:'Mettre en pause',play:'Reprendre',show:'Afficher le mot de passe',hide:'Masquer le mot de passe'},
    en:{working:'Working…',done:'Request received.',error:'Something went wrong.',confirm:'Permanently delete this account?',copied:'Link copied.',login:'Sign in to save this story.',pause:'Pause',play:'Resume',show:'Show password',hide:'Hide password'},
    ar:{working:'جارٍ المعالجة…',done:'تم استلام الطلب.',error:'حدث خطأ.',confirm:'هل تريد حذف هذا الحساب نهائيًا؟',copied:'تم نسخ الرابط.',login:'سجّل الدخول لحفظ المقال.',pause:'إيقاف مؤقت',play:'استئناف',show:'إظهار كلمة المرور',hide:'إخفاء كلمة المرور'},
    es:{working:'Procesando…',done:'Solicitud recibida.',error:'Ha ocurrido un error.',confirm:'¿Eliminar definitivamente esta cuenta?',copied:'Enlace copiado.',login:'Accede para guardar este artículo.',pause:'Pausar',play:'Reanudar',show:'Mostrar contraseña',hide:'Ocultar contraseña'},
    pt:{working:'A processar…',done:'Pedido recebido.',error:'Ocorreu um erro.',confirm:'Eliminar esta conta definitivamente?',copied:'Link copiado.',login:'Entre para guardar este artigo.',pause:'Pausar',play:'Retomar',show:'Mostrar palavra-passe',hide:'Ocultar palavra-passe'}
  }[locale];
  const reduced = matchMedia('(prefers-reduced-motion: reduce)');
  const toast = document.querySelector('#toast');
  let toastTimer;
  function notify(message){ if(!toast)return; toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.hidden=true,4500); }
  async function request(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options});let data;try{data=await response.json()}catch{data={}}if(!response.ok){const error=Error(data.error||text.error);Object.assign(error,data);throw error}return data;}
  const json = body => ({headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
  function formMessage(form,message){const element=form.querySelector('.form-error');if(element){element.textContent=message;element.hidden=!message;}else notify(message);}
  function setBusy(form,busy){const button=form.querySelector('[type=submit]');if(button)button.disabled=busy;}
  const menu = document.querySelector('#site-menu');const toggle=document.querySelector('#menu-toggle');
  const turnstileWidgets=new Map();
  function resetTurnstile(form){const id=turnstileWidgets.get(form);if(id!==undefined&&window.turnstile)window.turnstile.reset(id);}
  async function setupTurnstile(){const forms=[...document.querySelectorAll('form[data-turnstile]')];if(!forms.length)return;try{const config=await request('/api/config');if(!config.turnstile?.enabled)return;await new Promise((resolve,reject)=>{if(window.turnstile)return resolve();const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.defer=true;script.onload=resolve;script.onerror=reject;document.head.append(script);});forms.forEach(form=>{const mount=document.createElement('div');mount.className='turnstile-widget';const submit=form.querySelector('[type=submit]');if(submit?.parentElement===form)form.insertBefore(mount,submit);else form.appendChild(mount);turnstileWidgets.set(form,window.turnstile.render(mount,{sitekey:config.turnstile.siteKey,theme:'auto'}));});}catch(error){console.error('turnstile_setup_failed',error)}}
  setupTurnstile();
  function closeMenu(){if(!menu||menu.hidden)return;menu.hidden=true;toggle.setAttribute('aria-expanded','false');}
  if(toggle&&menu){toggle.addEventListener('click',()=>{const open=menu.hidden;menu.hidden=!open;toggle.setAttribute('aria-expanded',String(open));});document.addEventListener('pointerdown',event=>{if(!menu.contains(event.target)&&!toggle.contains(event.target))closeMenu();});document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeMenu();toggle.focus({preventScroll:true});}});menu.addEventListener('click',event=>{if(event.target.closest('a,[data-admin-view],[data-contributor-view]'))closeMenu();});menu.querySelectorAll('.menu-role details').forEach(details=>details.addEventListener('toggle',()=>{if(!details.open)return;menu.querySelectorAll('.menu-role details[open]').forEach(other=>{if(other!==details)other.open=false;});}));}
  const navigationKey='tamusni:pending-navigation';
  let navigationTimer=0;
  function navigateInternal(target,{preserveScroll=false}={}){
    const next=new URL(target,location.href);
    if(next.origin!==location.origin)return location.assign(next.href);
    if(preserveScroll){try{sessionStorage.setItem(navigationKey,JSON.stringify({path:next.pathname+next.search,scrollY:scrollY}));}catch{}}
    if(reduced.matches)return location.assign(next.href);
    if(navigationTimer)return;
    root.classList.add('is-page-leaving');
    navigationTimer=window.setTimeout(()=>location.assign(next.href),150);
  }
  function restoreLanguageScroll(){
    try{const pending=JSON.parse(sessionStorage.getItem(navigationKey)||'null');if(!pending||pending.path!==location.pathname+location.search)return;sessionStorage.removeItem(navigationKey);requestAnimationFrame(()=>scrollTo({top:Math.max(0,Number(pending.scrollY)||0),behavior:'instant'}));}catch{}
  }
  restoreLanguageScroll();
  addEventListener('pageshow',event=>{if(event.persisted)root.classList.remove('is-page-leaving');});
  document.addEventListener('click',event=>{
    if(event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;
    const link=event.target.closest('a[href]');if(!link||link.target||link.hasAttribute('download'))return;
    const next=new URL(link.href,location.href);
    if(next.origin!==location.origin||next.pathname.startsWith('/api/')||next.hash&&next.pathname===location.pathname&&next.search===location.search)return;
    event.preventDefault();navigateInternal(next.href);
  });
  const language=document.querySelector('#language');language?.addEventListener('change',()=>{const segments=location.pathname.split('/').filter(Boolean);if(['fr','ar','en','es','pt'].includes(segments[0]))segments.shift();navigateInternal(`/${language.value}/${segments.length?segments.join('/')+'/':''}${location.search}`,{preserveScroll:true});});
  const footerContact=document.querySelector('.site-footer .footer-trust:last-child');
  if(footerContact&&!footerContact.querySelector('.footer-social')){const social=document.createElement('nav');social.className='footer-social';social.setAttribute('aria-label','Réseaux sociaux');social.innerHTML='<a href="https://x.com/getbnhdh89514" rel="me noopener" target="_blank">X</a><a href="https://www.instagram.com/tam.usni/" rel="me noopener" target="_blank">Instagram</a><a href="https://web.facebook.com/profile.php?id=61595345005345" rel="me noopener" target="_blank">Facebook</a><a href="https://www.youtube.com/@Tamusni-i7h" rel="me noopener" target="_blank">YouTube</a>';footerContact.append(social);}
  document.querySelectorAll('form[data-auto-submit] select').forEach(select=>select.addEventListener('change',()=>select.form?.requestSubmit()));
  document.querySelector('#logout')?.addEventListener('click',async()=>{try{await request('/api/auth/logout',{method:'POST'});location.assign(`/${locale}/`);}catch(error){notify(error.message);}});
  let lastY=scrollY,scrolledMenuY=scrollY,scrollDirection='none';const header=document.querySelector('#site-header'),topButton=document.querySelector('#back-top');let scrollScheduled=false;
  function updateScroll(){const y=scrollY;const footer=document.querySelector('.site-footer');scrollDirection=y<lastY-5?'up':y>lastY+5?'down':scrollDirection;if(innerWidth<650){if(y>130&&y>lastY+5)header?.classList.add('is-hidden');else if(y<lastY-5||y<60)header?.classList.remove('is-hidden');}else header?.classList.remove('is-hidden');if(menu&&!menu.hidden&&Math.abs(y-scrolledMenuY)>160){closeMenu();}else if(menu?.hidden)scrolledMenuY=y;if(topButton){topButton.hidden=y<Math.max(700,innerHeight*1.2);if(footer&&footer.getBoundingClientRect().top<innerHeight-90)topButton.style.bottom=`${Math.max(22,innerHeight-footer.getBoundingClientRect().top+18)}px`;else topButton.style.bottom='22px';}lastY=y;scrollScheduled=false;}
  function returnToTop(){root.scrollTop=0;document.body.scrollTop=0;document.scrollingElement?.scrollTo({top:0,behavior:'instant'});}
  addEventListener('scroll',()=>{if(!scrollScheduled){scrollScheduled=true;requestAnimationFrame(updateScroll)}},{passive:true});updateScroll();topButton?.addEventListener('click',returnToTop);
  const revealItems=[...document.querySelectorAll('.reveal')];if(reduced.matches||!('IntersectionObserver'in window))revealItems.forEach(node=>node.classList.add('is-visible'));else{const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;const returning=scrollDirection==='up'&&entry.target.dataset.tamusniRevealed==='true';entry.target.classList.add('is-visible');entry.target.dataset.tamusniRevealed='true';if(returning){entry.target.classList.remove('scroll-return');requestAnimationFrame(()=>entry.target.classList.add('scroll-return'));}})},{threshold:.06,rootMargin:'0px 0px 70px 0px'});revealItems.forEach(node=>observer.observe(node));}
  const heroSlides=[...document.querySelectorAll('.hero-slide')];let heroIndex=0,heroPaused=false;const heroSection=document.querySelector('.hero-section');
  function showHero(index){if(!heroSlides.length)return;heroIndex=(index+heroSlides.length)%heroSlides.length;heroSlides.forEach((slide,i)=>{const active=i===heroIndex;slide.classList.toggle('is-current',active);slide.toggleAttribute('inert',!active);slide.setAttribute('aria-hidden',String(!active));});const counter=document.querySelector('#hero-index');if(counter)counter.textContent=String(heroIndex+1).padStart(2,'0');}
  const popularTrack=document.querySelector('#popular-track');const popularCards=[...(popularTrack?.querySelectorAll('.popular-card')||[])];let popularIndex=popularCards.length>1?1:0,popularPaused=false;
  function showPopular(index){if(!popularCards.length)return;popularIndex=(index+popularCards.length)%popularCards.length;popularCards.forEach((card,i)=>card.classList.toggle('is-active',i===popularIndex));if(!popularTrack)return;const card=popularCards[popularIndex],trackRect=popularTrack.getBoundingClientRect(),cardRect=card.getBoundingClientRect();const horizontalDelta=cardRect.left+cardRect.width/2-(trackRect.left+trackRect.width/2);if(Math.abs(horizontalDelta)>1)popularTrack.scrollBy({left:horizontalDelta,top:0,behavior:reduced.matches?'instant':'smooth'});}
  document.querySelectorAll('[data-carousel]').forEach(button=>button.addEventListener('click',()=>{const delta=Number(button.dataset.direction);if(button.dataset.carousel==='hero'){showHero(heroIndex+delta);heroPaused=true;}else{showPopular(popularIndex+delta);popularPaused=true;}}));
  document.querySelectorAll('[data-pause]').forEach(button=>button.addEventListener('click',()=>{const isHero=button.dataset.pause==='hero';if(isHero)heroPaused=!heroPaused;else popularPaused=!popularPaused;const paused=isHero?heroPaused:popularPaused;button.textContent=paused?'▶':'Ⅱ';button.setAttribute('aria-label',paused?text.play:text.pause);}));
  if(!reduced.matches){if(heroSlides.length>1)setInterval(()=>{if(!heroPaused&&!document.hidden)showHero(heroIndex+1)},3000);if(popularCards.length>1)setInterval(()=>{if(!popularPaused&&!document.hidden)showPopular(popularIndex+1)},3000);}
  for(const [element,setPause] of [[heroSection,value=>heroPaused=value],[popularTrack,value=>popularPaused=value]]){if(!element)continue;element.addEventListener('pointerenter',()=>setPause(true));element.addEventListener('pointerleave',()=>setPause(false));element.addEventListener('focusin',()=>setPause(true));element.addEventListener('touchstart',()=>setPause(true),{passive:true});}
  if(popularTrack){let timer;popularTrack.addEventListener('scroll',()=>{clearTimeout(timer);timer=setTimeout(()=>{const center=popularTrack.getBoundingClientRect().left+popularTrack.clientWidth/2;let nearest=0,distance=Infinity;popularCards.forEach((card,i)=>{const rect=card.getBoundingClientRect();const d=Math.abs(rect.left+rect.width/2-center);if(d<distance){nearest=i;distance=d;}});popularIndex=nearest;popularCards.forEach((card,i)=>card.classList.toggle('is-active',i===nearest));},100)},{passive:true});}
  let touchX;heroSection?.addEventListener('touchstart',event=>{touchX=event.touches[0].clientX;heroPaused=true;},{passive:true});heroSection?.addEventListener('touchend',event=>{if(touchX==null)return;const distance=event.changedTouches[0].clientX-touchX;if(Math.abs(distance)>45)showHero(heroIndex+(distance<0?1:-1));touchX=null;},{passive:true});
  document.querySelector('#newsletter-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;setBusy(form,true);try{const values=Object.fromEntries(new FormData(form));Object.assign(values,{email:form.email.value,locale,company:form.company?.value||''});const data=await request('/api/newsletter',{method:'POST',...json(values)});notify(data.message||text.done);if(data.requiresAuth&&data.redirect){setTimeout(()=>location.assign(data.redirect),450);return}form.reset();}catch(error){notify(error.message);resetTurnstile(form)}finally{setBusy(form,false)}});
  document.querySelectorAll('.show-password').forEach(button=>button.addEventListener('click',()=>{const input=button.parentElement.querySelector('input');input.type=input.type==='password'?'text':'password';button.setAttribute('aria-label',input.type==='password'?text.show:text.hide);button.setAttribute('title',input.type==='password'?text.show:text.hide);}));
  const loginForm=document.querySelector('#login-form'),signupForm=document.querySelector('#signup-form');
  if(loginForm||signupForm)request('/api/newsletter/intent').then(data=>{const input=(loginForm||signupForm).querySelector('input[name=email]');if(data.intent?.email&&input&&!input.value)input.value=data.intent.email}).catch(()=>{});
  if(new URLSearchParams(location.search).get('newsletter')==='success')notify(locale==='ar'?'تم تفعيل اشتراكك في النشرة الأسبوعية.':locale==='en'?'Your weekly review subscription is active.':locale==='es'?'Tu suscripción semanal está activa.':locale==='pt'?'A sua subscrição semanal está ativa.':'Votre inscription à la revue hebdomadaire est active.');
  async function finishAuth(form,endpoint,values){setBusy(form,true);formMessage(form,text.working);try{const data=await request(endpoint,{method:'POST',...json(values)});if(data.mfaRequired){form.innerHTML=`<label>Code<input name="code" inputmode="numeric" pattern="[0-9]{6}" minlength="6" maxlength="6" autocomplete="one-time-code" required></label><button class="primary-button" type="submit">${text.done}</button><p class="form-error" role="alert" hidden></p>`;form.dataset.mfa='true';form.querySelector('input').focus({preventScroll:true});return;}if(data.verificationRequired){location.assign(data.redirect||`/${locale}/connexion/?verification=pending`);return}const destinations={'/admin/':`/${locale}/admin/`,'/contributeur/':`/${locale}/contributeur/`,'/mon-espace/':`/${locale}/mon-espace/`},destination=data.redirect||'/mon-espace/';location.assign(destinations[destination]||(destination.startsWith('/')?`/${locale}${destination}`:`/${locale}/mon-espace/`));}catch(error){formMessage(form,error.message);resetTurnstile(form);if(error.code==='EMAIL_NOT_VERIFIED'&&error.redirect){location.assign(error.redirect);return}if(error.code==='EMAIL_NOT_VERIFIED')document.querySelector('#resend-verification')?.removeAttribute('hidden')}finally{setBusy(form,false)}}
  loginForm?.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));if(form.newsletterConsent)values.newsletterConsent=form.newsletterConsent.checked;finishAuth(form,form.dataset.mfa?'/api/auth/mfa-login':'/api/auth/login',values);});
  function selectedTopics(form){return [...form.querySelectorAll('input[name="preferredTopics"]:checked')].map(input=>input.value);}
  const oauthSignupKey='tamusni:oauth-signup',oauthTokenKey='tamusni:oauth-token';
  function oauthProfileMessage(){return locale==='ar'?'أكمل معلومات حسابك لإنهاء التسجيل عبر Google.':locale==='en'?'Complete your account details to finish signing up with Google.':locale==='es'?'Completa los datos de tu cuenta para terminar el registro con Google.':locale==='pt'?'Complete os dados da sua conta para concluir o registo com o Google.':'Complétez les informations de votre compte pour terminer l’inscription avec Google.';}
  function prepareOauthSignup(accessToken){if(!signupForm)return false;signupForm.dataset.oauthToken=accessToken;signupForm.querySelector('input[name=email]').closest('label').hidden=true;signupForm.querySelector('input[name=password]').closest('label').hidden=true;signupForm.querySelector('input[name=email]').required=false;signupForm.querySelector('input[name=password]').required=false;formMessage(signupForm,oauthProfileMessage());return true;}
  document.querySelector('.google-button')?.addEventListener('click',event=>{if(!signupForm)return;const firstName=signupForm.firstName?.value.trim()||'',lastName=signupForm.lastName?.value.trim()||'',preferredTopics=selectedTopics(signupForm);if(firstName.length<2||lastName.length<2||!preferredTopics.length||!signupForm.termsAccepted.checked){event.preventDefault();if(firstName.length<2)signupForm.firstName?.reportValidity();else if(lastName.length<2)signupForm.lastName?.reportValidity();else if(!preferredTopics.length)formMessage(signupForm,locale==='fr'?'Choisissez au moins une rubrique avant de continuer avec Google.':oauthProfileMessage());else signupForm.termsAccepted?.reportValidity();return;}sessionStorage.setItem(oauthSignupKey,JSON.stringify({firstName,lastName,preferredTopics,termsAccepted:true,sponsoredEmail:signupForm.sponsoredEmail.checked}));});
  signupForm?.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));values.preferredTopics=selectedTopics(form);if(!values.preferredTopics.length){formMessage(form,locale==='fr'?'Choisissez au moins une rubrique.':text.error);return;}values.locale=locale;values.termsAccepted=form.termsAccepted.checked;values.sponsoredEmail=form.sponsoredEmail.checked;values.newsletterConsent=new URLSearchParams(location.search).get('newsletter')==='1';if(form.dataset.oauthToken){values.accessToken=form.dataset.oauthToken;finishAuth(form,'/api/auth/oauth-session',values)}else finishAuth(form,'/api/auth/register',values);});
  document.querySelector('#resend-verification')?.addEventListener('click',async event=>{const button=event.currentTarget,email=loginForm?.email?.value;if(!email){loginForm?.email?.focus({preventScroll:true});return}button.disabled=true;try{const data=await request('/api/auth/resend-verification',{method:'POST',...json({email,locale})});formMessage(loginForm,data.message||text.done)}catch(error){formMessage(loginForm,error.message)}finally{button.disabled=false}});
  if(loginForm){const verification=new URLSearchParams(location.search).get('verification');if(verification){const messages={fr:{pending:'Compte créé. Consultez votre e-mail pour confirmer votre adresse.',success:'Adresse confirmée. Vous pouvez maintenant vous connecter.',invalid:'Ce lien de confirmation est invalide ou expiré.'},en:{pending:'Account created. Check your email to confirm your address.',success:'Address confirmed. You can now sign in.',invalid:'This confirmation link is invalid or expired.'},ar:{pending:'تم إنشاء الحساب. راجع بريدك لتأكيد العنوان.',success:'تم تأكيد العنوان. يمكنك تسجيل الدخول الآن.',invalid:'رابط التأكيد غير صالح أو منتهي الصلاحية.'},es:{pending:'Cuenta creada. Revisa tu correo para confirmar la dirección.',success:'Dirección confirmada. Ya puedes acceder.',invalid:'El enlace de confirmación no es válido o ha caducado.'},pt:{pending:'Conta criada. Consulte o e-mail para confirmar o endereço.',success:'Endereço confirmado. Já pode entrar.',invalid:'A ligação de confirmação é inválida ou expirou.'}};formMessage(loginForm,messages[locale]?.[verification]||text.error);if(verification!=='success')document.querySelector('#resend-verification')?.removeAttribute('hidden')}}
  const hash=new URLSearchParams(location.hash.slice(1)),storedOauthToken=sessionStorage.getItem(oauthTokenKey),accessToken=hash.get('access_token')||storedOauthToken;if(accessToken&&(loginForm||signupForm)){const newsletterConsent=new URLSearchParams(location.search).get('newsletter')==='1';history.replaceState(null,'',location.pathname+location.search);if(signupForm){let profile;try{profile=JSON.parse(sessionStorage.getItem(oauthSignupKey)||'null')}catch{}request('/api/auth/oauth-session',{method:'POST',...json({accessToken,locale,newsletterConsent,...(profile||{})})}).then(data=>{sessionStorage.removeItem(oauthSignupKey);sessionStorage.removeItem(oauthTokenKey);const destinations={'/admin/':`/${locale}/admin/`,'/contributeur/':`/${locale}/contributeur/`,'/mon-espace/':`/${locale}/mon-espace/`};location.assign(destinations[data.redirect]||data.redirect||`/${locale}/mon-espace/`);}).catch(error=>{if(error.code!=='OAUTH_PROFILE_REQUIRED'){formMessage(signupForm,error.message);return;}prepareOauthSignup(accessToken);});}else request('/api/auth/oauth-session',{method:'POST',...json({accessToken,locale,newsletterConsent})}).then(data=>{const destinations={'/admin/':`/${locale}/admin/`,'/contributeur/':`/${locale}/contributeur/`,'/mon-espace/':`/${locale}/mon-espace/`};location.assign(destinations[data.redirect]||data.redirect||`/${locale}/mon-espace/`);}).catch(error=>{if(error.code!=='OAUTH_PROFILE_REQUIRED'){formMessage(loginForm,error.message);return;}sessionStorage.setItem(oauthTokenKey,accessToken);location.assign(`/${locale}/inscription/?oauth=google${newsletterConsent?'&newsletter=1':''}`);});}
  const resetDialog=document.querySelector('#reset-dialog');document.querySelector('#forgot-trigger')?.addEventListener('click',()=>{resetDialog.showModal();resetDialog.querySelector('input').focus({preventScroll:true});});document.querySelector('#reset-cancel')?.addEventListener('click',()=>resetDialog.close());document.querySelector('#reset-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;setBusy(form,true);try{const values=Object.fromEntries(new FormData(form));values.locale=locale;await request('/api/auth/forgot-password',{method:'POST',...json(values)});resetDialog.close();notify(text.done);}catch(error){formMessage(form,error.message);resetTurnstile(form)}finally{setBusy(form,false)}});
  const verificationForm=document.querySelector('#verification-form');if(verificationForm){const params=new URLSearchParams(location.search);verificationForm.email.value=params.get('email')||'';verificationForm.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;setBusy(form,true);try{const data=await request('/api/auth/verify-email',{method:'POST',...json({email:form.email.value,code:form.code.value,locale})});location.assign(data.redirect||`/${locale}/mon-espace/`)}catch(error){formMessage(form,error.message)}finally{setBusy(form,false)}});document.querySelector('#verification-resend')?.addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;try{const values=Object.fromEntries(new FormData(verificationForm));values.locale=locale;const data=await request('/api/auth/resend-verification',{method:'POST',...json(values)});formMessage(verificationForm,data.message||text.done);resetTurnstile(verificationForm)}catch(error){formMessage(verificationForm,error.message);resetTurnstile(verificationForm)}finally{button.disabled=false}})}
  document.querySelector('#reset-password-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;setBusy(form,true);try{const token=new URLSearchParams(location.search).get('token')||'';const values=Object.fromEntries(new FormData(form));values.token=token;values.locale=locale;const data=await request('/api/auth/reset-password',{method:'POST',...json(values)});location.assign(data.redirect||`/${locale}/connexion/?password=changed`)}catch(error){formMessage(form,error.message)}finally{setBusy(form,false)}});
  const article=document.querySelector('.article-page');if(article){const slug=article.dataset.slug,post=body=>request(`/api/content/${encodeURIComponent(slug)}`,{method:'POST',...json(body)});post({action:'view',progress:0}).then(data=>{document.querySelector('#view-count').textContent=`${data.views} ${document.querySelector('#view-count').textContent.split(' ').slice(1).join(' ')}`;document.querySelector('#like-count').textContent=data.likes;}).catch(()=>{});document.querySelector('.like-action')?.addEventListener('click',async event=>{const button=event.currentTarget;try{const data=await post({action:'like'});document.querySelector('#like-count').textContent=data.likes;button.setAttribute('aria-pressed',String(data.liked));}catch(error){notify(error.message)}});document.querySelector('.save-action')?.addEventListener('click',async event=>{const button=event.currentTarget;if(document.body.dataset.auth!=='true'){notify(text.login);return;}try{await request('/api/favorites',{method:'POST',...json({itemId:article.dataset.itemId,itemType:'article',title:article.dataset.title,url:location.pathname})});button.setAttribute('aria-pressed','true');notify(text.done)}catch(error){notify(error.message)}});document.querySelector('.share-action')?.addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:article.dataset.title,url:location.href});else{await navigator.clipboard.writeText(location.href);notify(text.copied)}}catch{}});}
  document.querySelector('#profile-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const preferredTopics=selectedTopics(form);if(!preferredTopics.length){formMessage(form,locale==='fr'?'Choisissez au moins une rubrique.':text.error);return;}setBusy(form,true);try{const {profile}=await request('/api/account');const data=Object.fromEntries(new FormData(form));Object.assign(data,{preferredTopics,bio:profile.bio||'',avatarUrl:profile.avatar_url||'',language:locale,theme:'auto',textSize:profile.text_size||'normal',density:profile.display_density||'comfortable',notifications:Boolean(profile.notifications_enabled),sponsoredInApp:Boolean(profile.sponsored_in_app),sponsoredEmail:form.sponsoredEmail.checked});await request('/api/account',{method:'PATCH',...json(data)});notify(text.done)}catch(error){formMessage(form,error.message)}finally{setBusy(form,false)}});
  document.querySelector('#password-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;setBusy(form,true);try{await request('/api/account',{method:'PATCH',...json({...Object.fromEntries(new FormData(form)),action:'password'})});form.reset();notify(text.done)}catch(error){formMessage(form,error.message)}finally{setBusy(form,false)}});
  document.querySelector('#delete-request-form')?.addEventListener('submit',async event=>{event.preventDefault();if(!confirm(text.confirm))return;const form=event.currentTarget;setBusy(form,true);try{const data=await request('/api/account',{method:'PATCH',...json({action:'request-deletion',password:form.password.value,confirmDeletion:form.confirmDeletion.checked})});form.hidden=true;const confirmForm=document.querySelector('#delete-confirm-form');confirmForm.hidden=false;confirmForm.querySelector('input').focus({preventScroll:true});notify(data.message||text.done)}catch(error){formMessage(form,error.message)}finally{setBusy(form,false)}});
  document.querySelector('#delete-confirm-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;setBusy(form,true);try{await request('/api/account',{method:'DELETE',...json({code:form.code.value})});location.assign(`/${locale}/`)}catch(error){formMessage(form,error.message)}finally{setBusy(form,false)}});
})();
