(() => {
  const root = document.documentElement;
  const locale = document.body.dataset.locale || 'fr';
  const text = {
    fr:{working:'Traitement…',done:'Demande enregistrée.',error:'Une erreur est survenue.',confirm:'Supprimer définitivement ce compte ?',copied:'Lien copié.',login:'Connectez-vous pour enregistrer cet article.',pause:'Mettre en pause',play:'Reprendre',show:'Afficher le mot de passe',hide:'Masquer le mot de passe'},
    en:{working:'Working…',done:'Request received.',error:'Something went wrong.',confirm:'Permanently delete this account?',copied:'Link copied.',login:'Sign in to save this story.',pause:'Pause',play:'Resume',show:'Show password',hide:'Hide password'},
    ar:{working:'جارٍ المعالجة…',done:'تم استلام الطلب.',error:'حدث خطأ.',confirm:'هل تريد حذف هذا الحساب نهائيًا؟',copied:'تم نسخ الرابط.',login:'سجّل الدخول لحفظ المقال.',pause:'إيقاف مؤقت',play:'استئناف',show:'إظهار كلمة المرور',hide:'إخفاء كلمة المرور'},
    es:{working:'Procesando…',done:'Solicitud recibida.',error:'Ha ocurrido un error.',confirm:'¿Eliminar definitivamente esta cuenta?',copied:'Enlace copiado.',login:'Accede para guardar este artículo.',pause:'Pausar',play:'Reanudar',show:'Mostrar contraseña',hide:'Ocultar contraseña'},
    pt:{working:'A processar…',done:'Pedido recebido.',error:'Ocorreu um erro.',confirm:'Eliminar esta conta definitivamente?',copied:'Link copiado.',login:'Entre para guardar este artigo.',pause:'Pausar',play:'Retomar',show:'Mostrar palavra-passe',hide:'Ocultar palavra-passe'}
  }[locale];
  const reduced = matchMedia('(prefers-reduced-motion: reduce)');
  const toast = document.querySelector('#toast');
  let toastTimer;
  function notify(message){ if(!toast)return; toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.hidden=true,4500); }
  async function request(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options});let data;try{data=await response.json()}catch{data={}}if(!response.ok)throw Error(data.error||text.error);return data;}
  const json = body => ({headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
  function formMessage(form,message){const element=form.querySelector('.form-error');if(element){element.textContent=message;element.hidden=!message;}else notify(message);}
  function setBusy(form,busy){const button=form.querySelector('[type=submit]');if(button)button.disabled=busy;}
  const menu = document.querySelector('#site-menu');const toggle=document.querySelector('#menu-toggle');
  function closeMenu(){if(!menu||menu.hidden)return;menu.hidden=true;toggle.setAttribute('aria-expanded','false');}
  if(toggle&&menu){toggle.addEventListener('click',()=>{const open=menu.hidden;menu.hidden=!open;toggle.setAttribute('aria-expanded',String(open));});document.addEventListener('pointerdown',event=>{if(!menu.contains(event.target)&&!toggle.contains(event.target))closeMenu();});document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeMenu();}});menu.addEventListener('click',event=>{if(event.target.closest('a'))closeMenu();});}
  const language=document.querySelector('#language');language?.addEventListener('change',()=>{const segments=location.pathname.split('/').filter(Boolean);if(['fr','ar','en','es','pt'].includes(segments[0]))segments.shift();location.assign(`/${language.value}/${segments.length?segments.join('/')+'/':''}${location.search}`);});
  document.querySelector('#logout')?.addEventListener('click',async()=>{try{await request('/api/auth/logout',{method:'POST'});location.assign(`/${locale}/`);}catch(error){notify(error.message);}});
  let lastY=scrollY,scrolledMenuY=scrollY;const header=document.querySelector('#site-header'),topButton=document.querySelector('#back-top');let scrollScheduled=false;
  function updateScroll(){const y=scrollY;const footer=document.querySelector('.site-footer');if(innerWidth<650){if(y>130&&y>lastY+5)header?.classList.add('is-hidden');else if(y<lastY-5||y<60)header?.classList.remove('is-hidden');}else header?.classList.remove('is-hidden');if(menu&&!menu.hidden&&Math.abs(y-scrolledMenuY)>160){closeMenu();}else if(menu?.hidden)scrolledMenuY=y;if(topButton){topButton.hidden=y<Math.max(700,innerHeight*1.2);if(footer&&footer.getBoundingClientRect().top<innerHeight-90)topButton.style.bottom=`${Math.max(22,innerHeight-footer.getBoundingClientRect().top+18)}px`;else topButton.style.bottom='22px';}lastY=y;scrollScheduled=false;}
  addEventListener('scroll',()=>{if(!scrollScheduled){scrollScheduled=true;requestAnimationFrame(updateScroll)}},{passive:true});updateScroll();topButton?.addEventListener('click',()=>scrollTo({top:0,behavior:reduced.matches?'instant':'smooth'}));
  const revealItems=[...document.querySelectorAll('.reveal')];if(reduced.matches||!('IntersectionObserver'in window))revealItems.forEach(node=>node.classList.add('is-visible'));else{const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}})},{threshold:.06,rootMargin:'0px 0px 70px 0px'});revealItems.forEach(node=>observer.observe(node));}
  const heroSlides=[...document.querySelectorAll('.hero-slide')];let heroIndex=0,heroPaused=false;const heroSection=document.querySelector('.hero-section');
  function showHero(index){if(!heroSlides.length)return;heroIndex=(index+heroSlides.length)%heroSlides.length;heroSlides.forEach((slide,i)=>{const active=i===heroIndex;slide.classList.toggle('is-current',active);slide.toggleAttribute('inert',!active);slide.setAttribute('aria-hidden',String(!active));});const counter=document.querySelector('#hero-index');if(counter)counter.textContent=String(heroIndex+1).padStart(2,'0');}
  const popularTrack=document.querySelector('#popular-track');const popularCards=[...(popularTrack?.querySelectorAll('.popular-card')||[])];let popularIndex=popularCards.length>1?1:0,popularPaused=false;
  function showPopular(index){if(!popularCards.length)return;popularIndex=(index+popularCards.length)%popularCards.length;popularCards.forEach((card,i)=>card.classList.toggle('is-active',i===popularIndex));popularCards[popularIndex].scrollIntoView({inline:'center',block:'nearest',behavior:reduced.matches?'instant':'smooth'});}
  document.querySelectorAll('[data-carousel]').forEach(button=>button.addEventListener('click',()=>{const delta=Number(button.dataset.direction);if(button.dataset.carousel==='hero'){showHero(heroIndex+delta);heroPaused=true;}else{showPopular(popularIndex+delta);popularPaused=true;}}));
  document.querySelectorAll('[data-pause]').forEach(button=>button.addEventListener('click',()=>{const isHero=button.dataset.pause==='hero';if(isHero)heroPaused=!heroPaused;else popularPaused=!popularPaused;const paused=isHero?heroPaused:popularPaused;button.textContent=paused?'▶':'Ⅱ';button.setAttribute('aria-label',paused?text.play:text.pause);}));
  if(!reduced.matches){if(heroSlides.length>1)setInterval(()=>{if(!heroPaused&&!document.hidden)showHero(heroIndex+1)},3000);if(popularCards.length>1)setInterval(()=>{if(!popularPaused&&!document.hidden)showPopular(popularIndex+1)},3000);}
  for(const [element,setPause] of [[heroSection,value=>heroPaused=value],[popularTrack,value=>popularPaused=value]]){if(!element)continue;element.addEventListener('pointerenter',()=>setPause(true));element.addEventListener('pointerleave',()=>setPause(false));element.addEventListener('focusin',()=>setPause(true));element.addEventListener('touchstart',()=>setPause(true),{passive:true});}
  if(popularTrack){let timer;popularTrack.addEventListener('scroll',()=>{clearTimeout(timer);timer=setTimeout(()=>{const center=popularTrack.getBoundingClientRect().left+popularTrack.clientWidth/2;let nearest=0,distance=Infinity;popularCards.forEach((card,i)=>{const rect=card.getBoundingClientRect();const d=Math.abs(rect.left+rect.width/2-center);if(d<distance){nearest=i;distance=d;}});popularIndex=nearest;popularCards.forEach((card,i)=>card.classList.toggle('is-active',i===nearest));},100)},{passive:true});}
  let touchX;heroSection?.addEventListener('touchstart',event=>{touchX=event.touches[0].clientX;heroPaused=true;},{passive:true});heroSection?.addEventListener('touchend',event=>{if(touchX==null)return;const distance=event.changedTouches[0].clientX-touchX;if(Math.abs(distance)>45)showHero(heroIndex+(distance<0?1:-1));touchX=null;},{passive:true});
  document.querySelector('#newsletter-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;setBusy(form,true);try{const data=await request('/api/newsletter',{method:'POST',...json({email:form.email.value,locale})});notify(data.message||text.done);form.reset();}catch(error){notify(error.message)}finally{setBusy(form,false)}});
  document.querySelectorAll('.show-password').forEach(button=>button.addEventListener('click',()=>{const input=button.parentElement.querySelector('input');input.type=input.type==='password'?'text':'password';button.setAttribute('aria-label',input.type==='password'?text.show:text.hide);button.setAttribute('title',input.type==='password'?text.show:text.hide);}));
  const loginForm=document.querySelector('#login-form'),signupForm=document.querySelector('#signup-form');
  async function finishAuth(form,endpoint,values){setBusy(form,true);formMessage(form,text.working);try{const data=await request(endpoint,{method:'POST',...json(values)});if(data.mfaRequired){form.innerHTML=`<label>Code<input name="code" inputmode="numeric" pattern="[0-9]{6}" minlength="6" maxlength="6" autocomplete="one-time-code" required></label><button class="primary-button" type="submit">${text.done}</button><p class="form-error" role="alert" hidden></p>`;form.dataset.mfa='true';form.querySelector('input').focus();return;}location.assign(data.redirect?.startsWith('/admin')?'/admin/':`/${locale}/mon-espace/`);}catch(error){formMessage(form,error.message)}finally{setBusy(form,false)}}
  loginForm?.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));finishAuth(form,form.dataset.mfa?'/api/auth/mfa-login':'/api/auth/login',values);});
  signupForm?.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));values.termsAccepted=form.termsAccepted.checked;values.sponsoredEmail=form.sponsoredEmail.checked;if(form.dataset.oauthToken){values.accessToken=form.dataset.oauthToken;finishAuth(form,'/api/auth/oauth-session',values)}else finishAuth(form,'/api/auth/register',values);});
  const hash=new URLSearchParams(location.hash.slice(1));if(hash.get('access_token')&&(loginForm||signupForm)){const accessToken=hash.get('access_token');history.replaceState(null,'',location.pathname+location.search);if(signupForm){signupForm.dataset.oauthToken=accessToken;signupForm.querySelector('input[name=email]').closest('label').hidden=true;signupForm.querySelector('input[name=password]').closest('label').hidden=true;signupForm.querySelector('input[name=email]').required=false;signupForm.querySelector('input[name=password]').required=false;notify(text.done);}else finishAuth(loginForm,'/api/auth/oauth-session',{accessToken});}
  const resetDialog=document.querySelector('#reset-dialog');document.querySelector('#forgot-trigger')?.addEventListener('click',()=>{resetDialog.showModal();resetDialog.querySelector('input').focus();});document.querySelector('#reset-cancel')?.addEventListener('click',()=>resetDialog.close());document.querySelector('#reset-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;setBusy(form,true);try{await request('/api/auth/forgot-password',{method:'POST',...json({email:form.email.value})});resetDialog.close();notify(text.done);}catch(error){formMessage(form,error.message)}finally{setBusy(form,false)}});
  const article=document.querySelector('.article-page');if(article){const slug=article.dataset.slug,post=body=>request(`/api/content/${encodeURIComponent(slug)}`,{method:'POST',...json(body)});post({action:'view',progress:0}).then(data=>{document.querySelector('#view-count').textContent=`${data.views} ${document.querySelector('#view-count').textContent.split(' ').slice(1).join(' ')}`;document.querySelector('#like-count').textContent=data.likes;}).catch(()=>{});document.querySelector('.like-action')?.addEventListener('click',async event=>{const button=event.currentTarget;try{const data=await post({action:'like'});document.querySelector('#like-count').textContent=data.likes;button.setAttribute('aria-pressed',String(data.liked));}catch(error){notify(error.message)}});document.querySelector('.save-action')?.addEventListener('click',async event=>{const button=event.currentTarget;if(document.body.dataset.auth!=='true'){notify(text.login);return;}try{await request('/api/favorites',{method:'POST',...json({itemId:article.dataset.itemId,itemType:'article',title:article.dataset.title,url:location.pathname})});button.setAttribute('aria-pressed','true');notify(text.done)}catch(error){notify(error.message)}});document.querySelector('.share-action')?.addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:article.dataset.title,url:location.href});else{await navigator.clipboard.writeText(location.href);notify(text.copied)}}catch{}});}
  document.querySelector('#profile-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;setBusy(form,true);try{const {profile}=await request('/api/account');const data=Object.fromEntries(new FormData(form));Object.assign(data,{bio:profile.bio||'',avatarUrl:profile.avatar_url||'',language:locale,theme:'auto',textSize:profile.text_size||'normal',density:profile.display_density||'comfortable',notifications:Boolean(profile.notifications_enabled),sponsoredInApp:Boolean(profile.sponsored_in_app),sponsoredEmail:form.sponsoredEmail.checked});await request('/api/account',{method:'PATCH',...json(data)});notify(text.done)}catch(error){formMessage(form,error.message)}finally{setBusy(form,false)}});
  document.querySelector('#password-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;setBusy(form,true);try{await request('/api/account',{method:'PATCH',...json({...Object.fromEntries(new FormData(form)),action:'password'})});form.reset();notify(text.done)}catch(error){formMessage(form,error.message)}finally{setBusy(form,false)}});
  document.querySelector('#delete-form')?.addEventListener('submit',async event=>{event.preventDefault();if(!confirm(text.confirm))return;const form=event.currentTarget;setBusy(form,true);try{await request('/api/account',{method:'DELETE',...json({password:form.password.value})});location.assign(`/${locale}/`)}catch(error){formMessage(form,error.message)}finally{setBusy(form,false)}});
})();
