(function(){
  var page=document.body;var category=page.dataset.rubriqueCategory;var fallback=page.dataset.rubriqueFallback||'/images/editorial-ai-space.svg';var form=document.getElementById('rubrique-search');var results=document.getElementById('rubrique-results');var status=document.getElementById('rubrique-status');var title=document.getElementById('rubrique-title');var params=new URLSearchParams(location.search);var queryInput=form.elements.q;var sortInput=form.elements.sort;queryInput.value=params.get('q')||'';sortInput.value=params.get('sort')||'recent';document.title=(page.dataset.rubriqueTitle||category)+' — TAMUSNI';title.textContent=page.dataset.rubriqueTitle||category;
  function safeText(value){return String(value||'')}
  function isBrief(item){return /^BRÈVE\s*[—-]/i.test(safeText(item.title))}
  function iconButton(symbol,label){var button=document.createElement('button');button.type='button';button.className='rubrique-icon';button.textContent=symbol;button.setAttribute('aria-label',label);button.setAttribute('data-tooltip',label);return button}
  function share(item,button){var url=location.origin+'/articles/'+encodeURIComponent(item.slug);var finish=function(label){button.setAttribute('data-tooltip',label);setTimeout(function(){button.setAttribute('data-tooltip','Partager')},1800)};if(navigator.share){navigator.share({title:item.title,text:item.excerpt,url:url}).then(function(){finish('Partagé')}).catch(function(error){if(!error||error.name!=='AbortError')finish('Partage indisponible')})}else if(navigator.clipboard){navigator.clipboard.writeText(url).then(function(){finish('Lien copié')}).catch(function(){finish('Partage indisponible')})}else{finish('Partage indisponible')}}
  function save(item,button){fetch('/api/favorites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemId:item.id,itemType:item.type==='video'?'video':'article',title:item.title,url:'/articles/'+item.slug})}).then(function(response){if(response.status===401){location.href='/connexion/?next='+encodeURIComponent(location.pathname+location.search);return null}return response.json()}).then(function(data){if(data&&data.ok){button.setAttribute('aria-pressed','true');button.setAttribute('data-tooltip','Ajouté à voir plus tard');button.textContent='✓'}}).catch(function(){button.setAttribute('data-tooltip','Indisponible')})}
  function card(item){var article=document.createElement('article');article.className='rubrique-card';var link=document.createElement('a');link.className='rubrique-thumb';link.href='/articles/'+encodeURIComponent(item.slug);var image=document.createElement('img');image.src=item.cover_url||fallback;image.alt='Illustration éditoriale : '+safeText(item.title);image.loading='lazy';image.onerror=function(){this.src=fallback};link.append(image);var body=document.createElement('div');body.className='rubrique-card-body';var meta=document.createElement('span');meta.className='rubrique-meta';meta.textContent=isBrief(item)?'Brève':item.type==='video'?'Vidéo':'Article';var h3=document.createElement('h3');var heading=document.createElement('a');heading.href='/articles/'+encodeURIComponent(item.slug);heading.textContent=item.title;h3.append(heading);var excerpt=document.createElement('p');excerpt.textContent=item.excerpt;body.append(meta,h3,excerpt);if(item.source_url){var source=document.createElement('a');source.className='rubrique-source';source.href=item.source_url;source.target='_blank';source.rel='noopener noreferrer';source.textContent=item.source_label||'Consulter la source';body.append(source)}var actions=document.createElement('div');actions.className='rubrique-actions';var shareButton=iconButton('↗','Partager');shareButton.onclick=function(){share(item,shareButton)};var saveButton=iconButton('◷','Ajouter à voir plus tard');saveButton.onclick=function(){save(item,saveButton)};actions.append(shareButton,saveButton);article.append(link,body,actions);return article}
  function section(name,items,empty){var section=document.createElement('section');section.className='rubrique-section';var heading=document.createElement('h2');heading.textContent=name;var list=document.createElement('div');list.className='rubrique-list';if(items.length){items.forEach(function(item){list.append(card(item))})}else{var message=document.createElement('p');message.className='rubrique-empty';message.textContent=empty;list.append(message)}section.append(heading,list);return section}
  function reveal(){if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver'in window){page.classList.add('has-scroll-animations');var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}})},{threshold:.12});results.querySelectorAll('.rubrique-section,.rubrique-card').forEach(function(node){observer.observe(node)})}}
  function load(){var query=new URLSearchParams();query.set('category',category);query.set('sort',sortInput.value);if(queryInput.value.trim())query.set('q',queryInput.value.trim());history.replaceState(null,'',location.pathname+(queryInput.value.trim()||sortInput.value!=='recent'?'?'+query.toString().replace('category='+encodeURIComponent(category)+'&','') : ''));status.textContent='Chargement…';fetch('/api/content?'+query.toString()+'&limit=50').then(function(response){return response.json()}).then(function(data){var items=data.items||[];var articles=items.filter(function(item){return item.type!=='video'&&!isBrief(item)});var briefs=items.filter(isBrief);results.innerHTML='';results.append(section('Articles',articles,'Aucun article vérifié publié pour le moment.'),section('Brèves',briefs,'Aucune brève vérifiée publiée pour le moment.'),section('Interviews',[],'Aucune interview publiée pour le moment.'),section('Vidéos',[],'Aucune vidéo publiée pour le moment.'));status.textContent=items.length?items.length+' contenu(s) vérifié(s) trouvé(s).':'Aucun contenu vérifié trouvé.';reveal()}).catch(function(){status.textContent='Les contenus sont indisponibles pour le moment.'})}
  form.onsubmit=function(event){event.preventDefault();load()};sortInput.onchange=load;load();
})();
