(function(){
  var home=location.pathname==='/'||location.pathname==='/index.html';
  function el(tag,attrs,text){var n=document.createElement(tag);Object.keys(attrs||{}).forEach(function(k){n.setAttribute(k,attrs[k])});if(text)n.textContent=text;return n}
  function applyTheme(value){var theme=value==='dark'?'dark':'light';document.documentElement.setAttribute('data-theme',theme);try{localStorage.setItem('tamusni-theme',theme)}catch(e){}var button=document.getElementById('rail-theme');if(button){button.textContent=theme==='dark'?'☼':'◐';button.setAttribute('aria-label',theme==='dark'?'Activer le thème clair':'Activer le thème sombre');button.setAttribute('title',theme==='dark'?'Thème clair':'Thème sombre')}}
  var savedTheme=null;try{savedTheme=localStorage.getItem('tamusni-theme')}catch(e){}applyTheme(savedTheme||((window.matchMedia&&matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light'));
  if(document.body.hasAttribute('data-admin-shell')){var adminTheme=document.getElementById('rail-theme');if(adminTheme)adminTheme.onclick=function(){applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')};return}
  document.querySelectorAll('header:not(.global-shell-header):not(.rubrique-head),footer:not(.global-shell-footer)').forEach(function(node){node.remove()});
  if(!document.querySelector('.global-shell-header')){var header=el('header',{class:'global-shell-header'});var inner=el('div',{class:'global-shell-inner'});inner.append(el('a',{class:'global-shell-brand',href:'/'},'TAMUSNI'));header.append(inner);document.body.prepend(header)}
  var items=[['IA','Intelligence artificielle','/intelligence-artificielle/'],['✦','Innovation','/innovation/'],['⚙','Robotique','/robotique/'],['◈','Cybersécurité','/cybersecurite/'],['☼','Espace','/espace/']];
  var staticRail=document.querySelector('.tamusni-rail');if(staticRail)staticRail.remove();var rail=el('aside',{class:'tamusni-rail','aria-label':'Navigation TAMUSNI'});var railBrand=el('a',{class:'rail-brand',href:'/','aria-label':'TAMUSNI — Retour à l’accueil',title:'Retour à l’accueil'},'TAMUSNI');if(home)railBrand.setAttribute('aria-current','page');var nav=el('nav',{class:'tamusni-rail-nav'});items.forEach(function(item){var link=el('a',{class:'rail-item',href:item[2],'aria-label':item[1],'data-label':item[1],title:item[1]});if(location.pathname===item[2])link.setAttribute('aria-current','page');link.append(el('span',{class:'rail-symbol','aria-hidden':'true'},item[0]));nav.append(link)});
  var tools=el('div',{class:'tamusni-rail-tools'});var lang=el('select',{class:'rail-language',id:'global-language','aria-label':'Langue',title:'Langue'});lang.innerHTML='<option value="fr">FR</option><option value="ar">AR</option><option value="en">EN</option>';var theme=el('button',{class:'rail-item',type:'button','aria-label':'Changer de thème','data-label':'Thème',title:'Thème'},'◐');theme.id='rail-theme';var account=el('a',{class:'rail-item rail-account',href:'/connexion/','aria-label':'Inscription et connexion','data-label':'Inscription / Connexion',title:'Inscription / Connexion'},'◎');account.classList.add('rail-symbol');tools.append(lang,theme,account);rail.append(railBrand,nav,tools);document.body.append(rail);
  function enablePersonalRail(profile){
    var profileLink=el('a',{class:'rail-item rail-profile',href:'/mon-espace/#profile','aria-label':'Profil et réglages','data-label':'Profil et réglages',title:'Profil et réglages'},'◎');
    profileLink.classList.add('rail-symbol');nav.append(profileLink);
    if(profile.role==='ADMIN'){
      var administration=el('a',{class:'rail-item rail-administration',href:'/admin/','aria-label':'Administration','data-label':'Administration',title:'Administration'},'▦');
      administration.classList.add('rail-symbol');nav.append(administration);
    }
    account.href='#';account.textContent='↪';account.setAttribute('aria-label','Se déconnecter');account.dataset.label='Se déconnecter';account.title='Se déconnecter';
    account.onclick=async function(event){event.preventDefault();await fetch('/api/auth/logout',{method:'POST',credentials:'same-origin'});location.href='/'};
  }
  fetch('/api/account',{credentials:'same-origin',headers:{Accept:'application/json'}}).then(function(response){return response.ok?response.json():null}).then(function(data){if(data&&data.profile)enablePersonalRail(data.profile)}).catch(function(){});
  theme.onclick=function(){applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')};
  var language='fr';try{language=localStorage.getItem('tamusni-language')||((navigator.language||'fr').slice(0,2))}catch(e){}if(!['fr','ar','en'].includes(language))language='fr';lang.value=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';
  function updateDirection(value){document.documentElement.dir=value==='ar'?'rtl':'ltr';document.documentElement.lang=value;lang.value=value;railBrand.textContent=value==='ar'?'تاموسني':'TAMUSNI'}
  lang.addEventListener('change',function(){try{localStorage.setItem('tamusni-language',this.value)}catch(e){}updateDirection(this.value);window.dispatchEvent(new CustomEvent('tamusni-language-change',{detail:this.value}));if(/^\/articles\//.test(location.pathname)){var articleUrl=new URL(location.href);articleUrl.searchParams.set('lang',this.value);location.assign(articleUrl.toString());return}if(home&&typeof window.tamusniSetLanguage==='function')window.tamusniSetLanguage(this.value)});
  window.addEventListener('tamusni-language-change',function(event){updateDirection(event.detail)});
  document.querySelectorAll('.scroll-navigator,.shell-scroll').forEach(function(node){node.remove()});
  var footer=document.querySelector('.global-shell-footer');if(!footer){footer=el('footer',{class:'global-shell-footer'});document.body.append(footer)}footer.innerHTML='<div class="global-footer-inner"><div class="global-footer-follow">TAMUSNI</div><div class="global-footer-bottom"><span>© 2026 TAMUSNI · A&amp;B TECHNOLOGIES</span><span><a href="/mentions-legales/">Mentions légales</a><a href="/confidentialite/">Confidentialité</a><a href="/cookies/">Cookies</a></span></div></div>';
  function cropRail(){var sharedHeader=document.querySelector('.global-shell-header');var headerBottom=sharedHeader?Math.max(0,sharedHeader.getBoundingClientRect().bottom):0;var footerHeight=Math.max(0,footer.getBoundingClientRect().height);rail.style.top=headerBottom+'px';rail.style.bottom=footerHeight+'px';document.documentElement.style.setProperty('--shell-footer-space',footerHeight+'px')}cropRail();addEventListener('resize',cropRail);if(document.fonts&&document.fonts.ready)document.fonts.ready.then(cropRail);
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver'in window){var reveal=document.querySelectorAll('main>section,main article,.panel,.rubrique-result,.admin-panel-card');reveal.forEach(function(node,index){node.classList.add('scroll-reveal');node.style.setProperty('--reveal-delay',Math.min(index%6,4)*55+'ms')});var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('is-revealed');observer.unobserve(entry.target)}})},{threshold:.12});reveal.forEach(function(node){observer.observe(node)})}
})();
