(function(){
  var home=location.pathname==='/'||location.pathname==='/index.html';
  function el(tag,attrs,text){var n=document.createElement(tag);Object.keys(attrs||{}).forEach(function(k){n.setAttribute(k,attrs[k])});if(text)n.textContent=text;return n}
  function applyTheme(value){var theme=value==='dark'?'dark':'light';document.documentElement.setAttribute('data-theme',theme);try{localStorage.setItem('tamusni-theme',theme)}catch(e){}var button=document.getElementById('rail-theme');if(button)button.textContent=theme==='dark'?'☼':'◐'}
  var savedTheme=null;try{savedTheme=localStorage.getItem('tamusni-theme')}catch(e){}applyTheme(savedTheme||((window.matchMedia&&matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light'));
  document.querySelectorAll('header:not(.global-shell-header),footer').forEach(function(node){node.remove()});
  if(!document.querySelector('.global-shell-header')){var header=el('header',{class:'global-shell-header'});var inner=el('div',{class:'global-shell-inner'});inner.append(el('a',{class:'global-shell-brand',href:'/'},'TAMUSNI'));header.append(inner);document.body.prepend(header)}
  var items=[['AI','Intelligence','/recherche/?category=Intelligence'],['✦','Innovation & technologies','/recherche/?category=Innovation'],['⚙','Robotique','/recherche/?category=Robotique'],['◈','Cybersécurité','/recherche/?category=Cybers%C3%A9curit%C3%A9'],['◇','Espace','/recherche/?category=Espace']];
  var rail=el('aside',{class:'tamusni-rail','aria-label':'Navigation TAMUSNI'});var railBrand=el('a',{class:'rail-brand',href:'/','aria-label':'TAMUSNI — Retour à l’accueil',title:'Retour à l’accueil'},'TAMUSNI');var nav=el('nav',{class:'tamusni-rail-nav'});items.forEach(function(item){var link=el('a',{class:'rail-item',href:item[2],'aria-label':item[1],'data-label':item[1],title:item[1]});link.append(el('span',{class:'rail-symbol','aria-hidden':'true'},item[0]));nav.append(link)});
  var tools=el('div',{class:'tamusni-rail-tools'});var lang=el('select',{class:'rail-language',id:'global-language','aria-label':'Langue',title:'Langue'});lang.innerHTML='<option value="fr">FR</option><option value="ar">AR</option><option value="en">EN</option>';var theme=el('button',{class:'rail-item',type:'button','aria-label':'Changer de thème','data-label':'Thème',title:'Thème'},'◐');theme.id='rail-theme';var account=el('a',{class:'rail-item rail-account',href:'/connexion/','aria-label':'Inscription et connexion','data-label':'Inscription / Connexion',title:'Inscription / Connexion'},'◎');account.classList.add('rail-symbol');tools.append(lang,theme,account);rail.append(railBrand,nav,tools);document.body.append(rail);
  theme.onclick=function(){applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')};
  var language='fr';try{language=localStorage.getItem('tamusni-language')||((navigator.language||'fr').slice(0,2))}catch(e){}if(!['fr','ar','en'].includes(language))language='fr';lang.value=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';
  function updateDirection(value){document.documentElement.dir=value==='ar'?'rtl':'ltr';lang.value=value}
  lang.addEventListener('change',function(){try{localStorage.setItem('tamusni-language',this.value)}catch(e){}updateDirection(this.value);window.dispatchEvent(new CustomEvent('tamusni-language-change',{detail:this.value}));if(home&&typeof window.tamusniSetLanguage==='function')window.tamusniSetLanguage(this.value)});
  window.addEventListener('tamusni-language-change',function(event){updateDirection(event.detail)});
  document.querySelectorAll('.scroll-navigator,.shell-scroll').forEach(function(node){node.remove()});
  var footer=el('footer',{class:'global-shell-footer'});footer.innerHTML='<div class="global-footer-inner"><div class="global-footer-follow">Suivre TAMUSNI</div><div class="global-footer-social"><a href="#" aria-label="TAMUSNI sur X">X</a><a href="#" aria-label="TAMUSNI sur YouTube">YouTube</a><a href="#" aria-label="TAMUSNI sur Instagram">Instagram</a><a href="#" aria-label="TAMUSNI sur TikTok">TikTok</a><a href="#" aria-label="TAMUSNI sur Facebook">Facebook</a></div><div class="global-footer-bottom"><span>© 2026 TAMUSNI · A&amp;B TECHNOLOGIES</span><span><a href="/mentions-legales/">Mentions légales</a><a href="/confidentialite/">Confidentialité</a><a href="/cookies/">Cookies</a></span></div></div>';document.body.append(footer);
  function cropRail(){var sharedHeader=document.querySelector('.global-shell-header');var headerBottom=sharedHeader?Math.max(0,sharedHeader.getBoundingClientRect().bottom):0;var footerHeight=Math.max(0,footer.getBoundingClientRect().height);rail.style.top=headerBottom+'px';rail.style.bottom=footerHeight+'px';document.documentElement.style.setProperty('--shell-footer-space',footerHeight+'px')}cropRail();addEventListener('resize',cropRail);if(document.fonts&&document.fonts.ready)document.fonts.ready.then(cropRail);
})();
