(function(){
  var home=location.pathname==='/'||location.pathname==='/index.html';
  function el(tag,attrs,text){var n=document.createElement(tag);Object.keys(attrs||{}).forEach(function(k){n.setAttribute(k,attrs[k])});if(text)n.textContent=text;return n}
  function applyTheme(value){var theme=value==='dark'?'dark':'light';document.documentElement.setAttribute('data-theme',theme);try{localStorage.setItem('tamusni-theme',theme)}catch(e){}var button=document.getElementById('rail-theme');if(button)button.textContent=theme==='dark'?'☼':'◐'}
  var savedTheme=null;try{savedTheme=localStorage.getItem('tamusni-theme')}catch(e){}applyTheme(savedTheme||((window.matchMedia&&matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light'));
  var oldHeader=document.querySelector('.article-header,.top');if(oldHeader)oldHeader.remove();
  var homeHeader=document.querySelector('.site-header');
  if(homeHeader){var star=homeHeader.querySelector('.star');if(star)star.remove();var oldTools=homeHeader.querySelector('.masthead-tools');if(oldTools)oldTools.remove();var oldMenu=homeHeader.querySelector('.mobile-menu');if(oldMenu)oldMenu.remove();var oldScroll=document.querySelector('.scroll-navigator');if(oldScroll)oldScroll.remove()}
  if(!homeHeader){var header=el('header',{class:'global-shell-header'});var inner=el('div',{class:'global-shell-inner'});inner.append(el('a',{class:'global-shell-brand',href:'/'},'TAMUSNI'));header.append(inner);document.body.prepend(header)}
  var items=[['⌂','Accueil','/'],['AI','Intelligence','/recherche/?category=Intelligence'],['✦','Innovation','/recherche/?category=Innovation'],['▣','Technologies','/recherche/?category=Technologies'],['⚙','Robotique','/recherche/?category=Robotique'],['◈','Cybersécurité','/recherche/?category=Cybers%C3%A9curit%C3%A9'],['◌','Futur','/recherche/?category=Futur'],['◇','Espace','/recherche/?category=Espace'],['Σ','Sciences','/recherche/?category=Sciences'],['☷','Forum','/forums/']];
  var rail=el('aside',{class:'tamusni-rail','aria-label':'Navigation TAMUSNI'});var nav=el('nav',{class:'tamusni-rail-nav'});items.forEach(function(item){var link=el('a',{class:'rail-item',href:item[2],'aria-label':item[1],'data-label':item[1],title:item[1]});link.append(el('span',{class:'rail-symbol','aria-hidden':'true'},item[0]));nav.append(link)});
  var tools=el('div',{class:'tamusni-rail-tools'});var search=el('button',{class:'rail-item',type:'button','aria-label':'Rechercher','data-label':'Rechercher',title:'Rechercher'},'⌕');search.classList.add('rail-symbol');search.id='rail-search';var lang=el('select',{class:'rail-language',id:'global-language','aria-label':'Langue',title:'Langue'});lang.innerHTML='<option value="fr">FR</option><option value="ar">AR</option><option value="en">EN</option>';var theme=el('button',{class:'rail-item',type:'button','aria-label':'Changer de thème','data-label':'Thème',title:'Thème'},'◐');theme.id='rail-theme';var account=el('a',{class:'rail-item rail-account',href:'/connexion/','aria-label':'Inscription et connexion','data-label':'Inscription / Connexion',title:'Inscription / Connexion'},'◎');account.classList.add('rail-symbol');tools.append(search,lang,theme,account);rail.append(nav,tools);document.body.append(rail);
  search.onclick=function(){location.href='/recherche/'};theme.onclick=function(){applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')};
  var language='fr';try{language=localStorage.getItem('tamusni-language')||((navigator.language||'fr').slice(0,2))}catch(e){}if(!['fr','ar','en'].includes(language))language='fr';lang.value=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';
  function updateDirection(value){document.documentElement.dir=value==='ar'?'rtl':'ltr';lang.value=value}
  lang.addEventListener('change',function(){try{localStorage.setItem('tamusni-language',this.value)}catch(e){}updateDirection(this.value);window.dispatchEvent(new CustomEvent('tamusni-language-change',{detail:this.value}));if(home&&typeof window.tamusniSetLanguage==='function')window.tamusniSetLanguage(this.value)});
  window.addEventListener('tamusni-language-change',function(event){updateDirection(event.detail)});
  document.querySelectorAll('.scroll-navigator,.shell-scroll').forEach(function(node){node.remove()});
  if(!home&&!document.querySelector('.global-shell-footer')&&!document.querySelector('.site-footer')){var footer=el('footer',{class:'global-shell-footer'});footer.innerHTML='© 2026 TAMUSNI · A&amp;B TECHNOLOGIES <a href="/mentions-legales/">Mentions légales</a><a href="/confidentialite/">Confidentialité</a><a href="/cookies/">Cookies</a>';document.body.append(footer)}
})();
