(function(){
  var supported=['fr','en','ar'],current='fr';try{current=localStorage.getItem('tamusni-language')||((navigator.languages&&navigator.languages[0])||navigator.language||'fr').toLowerCase().split('-')[0]}catch(e){}if(!supported.includes(current))current='fr';
  var select=document.getElementById('global-language');if(!select)return;select.value=current;
  var nodes=Array.from(document.querySelectorAll('main h1,main h2,main h3,main h4,main p,main a,main button,main span,main label,main li,main time')).filter(function(node){return!node.children.length&&node.textContent.trim()});nodes.forEach(function(node){node.dataset.tamusniFr=node.textContent.trim()});
  async function apply(language){document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';nodes.forEach(function(node){node.textContent=node.dataset.tamusniFr});try{localStorage.setItem('tamusni-language',language)}catch(e){}if(language==='fr')return;var originals=nodes.map(function(node){return node.dataset.tamusniFr}),key='tamusni-page-v2-'+location.pathname+'-'+language,translations=null;try{translations=JSON.parse(localStorage.getItem(key)||'null')}catch(e){}
    if(!translations||translations.length!==originals.length){select.disabled=true;try{var chunks=[];for(var offset=0;offset<originals.length;offset+=80)chunks.push(originals.slice(offset,offset+80));var results=await Promise.all(chunks.map(function(texts){return fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:language,texts:texts})}).then(function(r){if(!r.ok)throw new Error('translation');return r.json()})}));translations=results.reduce(function(all,result){return all.concat(result.translations||[])},[]);try{localStorage.setItem(key,JSON.stringify(translations))}catch(e){}}catch(error){console.error(error);return}finally{select.disabled=false}}
    nodes.forEach(function(node,index){if(translations[index])node.textContent=translations[index]});
  }
  select.addEventListener('change',function(){apply(this.value)});window.addEventListener('tamusni-language-change',function(event){if(event.detail!==select.value){select.value=event.detail;apply(event.detail)}});apply(current);
})();
