import { NextResponse } from "next/server";
import { z } from "zod";
import { adminRepository } from "@/lib/db";
import { requireAdmin } from "@/lib/admin";
import { enforceRateLimit, enforceSameOrigin, readJson } from "@/lib/security";

const categories = ["Innovation", "Intelligence", "Technologies", "Robotique", "Cybersécurité", "Futur", "Espace", "Sciences"] as const;
const schema = z.object({ slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(120), type: z.enum(["ARTICLE", "BREVE", "VIDEO", "INTERVIEW"]), category: z.enum(categories), title: z.string().trim().min(5).max(180), subtitle: z.string().trim().min(10).max(420), imageUrl: z.string().trim().url().max(2048).optional().or(z.literal("")), videoUrl: z.string().trim().url().max(2048).optional().or(z.literal("")), body: z.string().trim().min(20).max(50000), status: z.enum(["DRAFT", "PUBLISHED"]) });
export async function GET() { const { response } = await requireAdmin(); if (response) return response; return NextResponse.json({ items: await adminRepository.listContent() }); }
export async function POST(request: Request) { const origin = enforceSameOrigin(request); if (origin) return origin; const rate = enforceRateLimit(request, "admin-content", 30, 900_000); if (rate) return rate; const { session, response } = await requireAdmin(); if (response || !session) return response!; try { const input = schema.parse(await readJson(request, 60_000)); const image = input.imageUrl || null, video = input.videoUrl || null; if ((input.type === "ARTICLE" || input.type === "BREVE") && !image) return NextResponse.json({ error: "Une image est requise pour un article ou une brève." }, { status: 400 }); if (input.type === "VIDEO" && !video) return NextResponse.json({ error: "Une URL vidéo est requise pour une vidéo." }, { status: 400 }); if (input.type === "INTERVIEW" && !image && !video) return NextResponse.json({ error: "Une image ou une vidéo est requise pour une interview." }, { status: 400 }); const item = await adminRepository.createContent({ slug: input.slug, type: input.type, category: input.category, title: input.title, subtitle: input.subtitle, image_url: image, video_url: video, body: input.body, status: input.status, author_name: session.name }); return NextResponse.json({ item }, { status: 201 }); } catch (error) { if (error instanceof z.ZodError) return NextResponse.json({ error: "Vérifiez les champs et les URLs du contenu." }, { status: 400 }); return NextResponse.json({ error: "Impossible d’enregistrer ce contenu. Le slug est peut-être déjà utilisé." }, { status: 400 }); } }
