import { cleanText, json, readBody, requireAdmin, sameOrigin } from "../../_lib/auth.js";
const types = new Set(["article", "video", "podcast"]); const statuses = new Set(["draft", "review", "scheduled", "published", "archived"]); const checks = new Set(["verified", "context", "correction", "opinion"]);
async function audit(context, admin, action, targetId, metadata={}) { await context.env.DB.prepare("INSERT INTO admin_audit_log(id,admin_user_id,action,target_type,target_id,metadata,created_at) VALUES(?,?,?,?,?,?,?)").bind(crypto.randomUUID(), admin.sub, action, "content", targetId, JSON.stringify(metadata), new Date().toISOString()).run(); }
export async function onRequestGet(context) {
  const admin=await requireAdmin(context);if(!admin)return json({error:"Accès réservé à l’administration."},403);
  const result=await context.env.DB.prepare("SELECT id,slug,type,status,title,category,author_name,fact_check_status,sponsored,published_at,scheduled_at,updated_at FROM content_items ORDER BY updated_at DESC LIMIT 100").all();return json({items:result.results||[]});
}
export async function onRequestPost(context) {
  if(!sameOrigin(context.request))return json({error:"Origine refusée."},403);const admin=await requireAdmin(context);if(!admin)return json({error:"Accès réservé à l’administration."},403);
  const body=await readBody(context.request);const title=cleanText(body.title,240);const slug=cleanText(body.slug,160).toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"");const type=types.has(body.type)?body.type:"article";const status=statuses.has(body.status)?body.status:"draft";const now=new Date().toISOString();
  if(title.length<5||slug.length<3)return json({error:"Titre ou URL invalide."},400);const id=crypto.randomUUID();
  await context.env.DB.prepare("INSERT INTO content_items(id,slug,type,status,title,excerpt,body,summary,category,author_name,cover_url,media_url,transcript,subtitles_url,fact_check_status,sponsored,sponsor_name,published_at,scheduled_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,slug,type,status,title,cleanText(body.excerpt,500),cleanText(body.body,15000),cleanText(body.summary,1000),cleanText(body.category,80)||"Actualité",cleanText(body.authorName,100)||"Rédaction TAMUSNI",/^https:\/\//.test(body.coverUrl||"")?body.coverUrl:null,/^https:\/\//.test(body.mediaUrl||"")?body.mediaUrl:null,cleanText(body.transcript,15000),/^https:\/\//.test(body.subtitlesUrl||"")?body.subtitlesUrl:null,checks.has(body.factCheckStatus)?body.factCheckStatus:"verified",body.sponsored?1:0,cleanText(body.sponsorName,100)||null,status==="published"?(body.publishedAt||now):null,status==="scheduled"?body.scheduledAt:null,now,now).run();
  const sourceUrl=cleanText(body.sourceUrl,500);const sourceLabel=cleanText(body.sourceLabel,200);if(/^https:\/\//i.test(sourceUrl)&&sourceLabel){await context.env.DB.prepare("INSERT INTO content_sources(id,content_id,label,url,publisher,created_at) VALUES(?,?,?,?,?,?)").bind(crypto.randomUUID(),id,sourceLabel,sourceUrl,cleanText(body.sourcePublisher,120),now).run()}
  const tagNames=String(body.tags||"").split(",").map((tag)=>cleanText(tag,60)).filter(Boolean).slice(0,10);for(const tagName of tagNames){const tagSlug=tagName.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");if(!tagSlug)continue;await context.env.DB.prepare("INSERT OR IGNORE INTO tags(id,slug,name) VALUES(?,?,?)").bind(crypto.randomUUID(),tagSlug,tagName).run();const tag=await context.env.DB.prepare("SELECT id FROM tags WHERE slug=?").bind(tagSlug).first();if(tag)await context.env.DB.prepare("INSERT OR IGNORE INTO content_tags(content_id,tag_id) VALUES(?,?)").bind(id,tag.id).run()}
  await audit(context,admin,"content.create",id,{slug,status});return json({ok:true,id,slug},201);
}
export async function onRequestPatch(context) {
  if(!sameOrigin(context.request))return json({error:"Origine refusée."},403);const admin=await requireAdmin(context);if(!admin)return json({error:"Accès réservé à l’administration."},403);const body=await readBody(context.request);const id=cleanText(body.id,160);const status=statuses.has(body.status)?body.status:null;if(!id||!status)return json({error:"Modification invalide."},400);const now=new Date().toISOString();const publishedAt=status==="published"?(body.publishedAt||now):null;const scheduledAt=status==="scheduled"?body.scheduledAt:null;
  await context.env.DB.prepare("UPDATE content_items SET status=?,published_at=COALESCE(?,published_at),scheduled_at=?,updated_at=? WHERE id=?").bind(status,publishedAt,scheduledAt,now,id).run();if(status==="published"){const item=await context.env.DB.prepare("SELECT title,slug,category FROM content_items WHERE id=?").bind(id).first();if(item)await context.env.DB.prepare("INSERT INTO notifications(id,user_id,title,url,created_at) SELECT lower(hex(randomblob(16))),user_id,?,?,? FROM topic_subscriptions WHERE LOWER(topic)=LOWER(?)").bind(`Nouveau contenu : ${item.title}`,`/articles/${item.slug}`,now,item.category).run()}await audit(context,admin,"content.status",id,{status});return json({ok:true});
}
