import { json, readBody, requireAdmin, sameOrigin } from "../../_lib/auth.js";
import { refreshEditionAnalytics } from "../../_lib/newsletter-service.js";
import { newsletterClock, sundayCycle } from "../../_lib/newsletter-core.js";

const pageSize=value=>Math.min(100,Math.max(10,Number(value)||30));
const safeLike=value=>`%${String(value||"").trim().toLowerCase().replace(/[%_]/g,"\\$&").slice(0,120)}%`;

export async function onRequestGet(context){
  if(!await requireAdmin(context))return json({error:"Accès réservé à l’administration."},403);const url=new URL(context.request.url),view=url.searchParams.get("view")||"overview";
  if(view==="subscribers"){const q=url.searchParams.get("q")||"",limit=pageSize(url.searchParams.get("limit")),offset=Math.max(0,Number(url.searchParams.get("offset"))||0);const rows=await context.env.DB.prepare("SELECT id,email,locale,status,subscribed_at,unsubscribed_at,brevo_sync_status,created_at FROM newsletter_subscribers WHERE lower(email) LIKE ? ORDER BY created_at DESC LIMIT ? OFFSET ?").bind(safeLike(q),limit,offset).all();return json({items:rows.results||[],limit,offset})}
  if(view==="edition"){const id=url.searchParams.get("id");let edition=await context.env.DB.prepare("SELECT * FROM newsletter_editions WHERE id=?").bind(id).first();if(!edition)return json({error:"Édition introuvable."},404);if(url.searchParams.get("refresh")==="1"&&edition.brevo_campaign_id)try{edition=await refreshEditionAnalytics(context.env,edition)}catch(error){console.error("newsletter_analytics_refresh_failed",error)}const [items,links]=await Promise.all([context.env.DB.prepare("SELECT i.position,i.is_highlight,i.score,c.title,c.slug,c.category FROM newsletter_edition_items i JOIN content_items c ON c.id=i.content_id WHERE i.edition_id=? ORDER BY i.position").bind(id).all(),context.env.DB.prepare("SELECT url,COUNT(*) AS clicks FROM newsletter_events WHERE campaign_id=? AND event_type='click' AND url IS NOT NULL GROUP BY url ORDER BY clicks DESC LIMIT 20").bind(String(edition.brevo_campaign_id||"")).all()]);return json({edition,items:items.results||[],links:links.results||[]})}
  const [subscribers,newSubscribers,editions,lastRun,recent]=await Promise.all([context.env.DB.prepare("SELECT COUNT(*) AS total,SUM(status='active') AS active,SUM(status='unsubscribed') AS unsubscribed,SUM(brevo_sync_status='error') AS sync_errors FROM newsletter_subscribers").first(),context.env.DB.prepare("SELECT COUNT(*) AS count FROM newsletter_subscribers WHERE created_at>=?").bind(new Date(Date.now()-7*86400000).toISOString()).first(),context.env.DB.prepare("SELECT COUNT(*) AS total,SUM(status='SENT') AS sent,SUM(COALESCE(sent_count,0)) AS emails,SUM(COALESCE(delivered_count,0)) AS delivered,SUM(COALESCE(open_count,0)) AS opens,SUM(COALESCE(click_count,0)) AS clicks,SUM(COALESCE(bounce_count,0)) AS bounces,SUM(COALESCE(error_count,0)) AS errors FROM newsletter_editions").first(),context.env.DB.prepare("SELECT * FROM newsletter_runs ORDER BY started_at DESC LIMIT 1").first(),context.env.DB.prepare("SELECT * FROM newsletter_editions ORDER BY created_at DESC LIMIT 30").all()]);const cycle=sundayCycle(new Date(),"Africa/Casablanca"),clock=newsletterClock(new Date(),"Africa/Casablanca");return json({subscribers:{...subscribers,new7d:Number(newSubscribers?.count||0)},totals:editions||{},lastRun:lastRun||null,nextRun:{cycleKey:cycle.cycleKey,localDate:cycle.localDate,time:"08:00",timeZone:"Africa/Casablanca",currentLocalDate:clock.date},editions:recent.results||[]})
}

export async function onRequestPost(context){if(!sameOrigin(context.request))return json({error:"Origine refusée."},403);if(!await requireAdmin(context))return json({error:"Accès réservé à l’administration."},403);const body=await readBody(context.request);if(body.action!=="refresh"||!body.id)return json({error:"Action invalide."},400);const edition=await context.env.DB.prepare("SELECT * FROM newsletter_editions WHERE id=?").bind(body.id).first();if(!edition)return json({error:"Édition introuvable."},404);try{return json({ok:true,edition:await refreshEditionAnalytics(context.env,edition)})}catch(error){return json({error:"Statistiques Brevo momentanément indisponibles."},502)}}
