import { cleanText, json, readBody, requireAdmin, sameOrigin } from '../../_lib/auth.js';
import { prepareSocialJobs, processSocialJobs } from '../../_lib/social-service.js';
const modes=new Set(['AUTO','MANUAL','PAUSED']);
export async function onRequestGet(context){if(!await requireAdmin(context))return json({error:'Accès réservé à l’administration.'},403);await prepareSocialJobs(context.env);const [accounts,publications,stats]=await Promise.all([context.env.DB.prepare('SELECT * FROM social_accounts ORDER BY platform').all(),context.env.DB.prepare("SELECT p.*,c.title,c.slug,c.category,c.type FROM social_publications p JOIN content_items c ON c.id=p.content_id ORDER BY p.created_at DESC LIMIT 150").all(),context.env.DB.prepare('SELECT status,COUNT(*) AS count FROM social_publications GROUP BY status').all()]);return json({mode:String(context.env.SOCIAL_PUBLISHING_MODE||'test').toLowerCase(),accounts:accounts.results||[],publications:publications.results||[],stats:stats.results||[]})}
export async function onRequestPost(context){if(!sameOrigin(context.request))return json({error:'Origine refusée.'},403);const admin=await requireAdmin(context);if(!admin)return json({error:'Accès réservé à l’administration.'},403);const body=await readBody(context.request),action=cleanText(body.action,40),id=cleanText(body.id,80),stamp=new Date().toISOString();
  if(action==='mode'){const platform=cleanText(body.platform,20),mode=modes.has(body.mode)?body.mode:null;if(!mode)return json({error:'Mode invalide.'},400);await context.env.DB.prepare('UPDATE social_accounts SET mode=?,updated_at=? WHERE platform=?').bind(mode,stamp,platform).run();return json({ok:true})}
  const job=id?await context.env.DB.prepare('SELECT * FROM social_publications WHERE id=?').bind(id).first():null;if(!job)return json({error:'Publication sociale introuvable.'},404);
  if(action==='cancel')await context.env.DB.prepare("UPDATE social_publications SET status='CANCELLED',updated_at=? WHERE id=? AND status NOT IN ('PUBLISHED','CANCELLED')").bind(stamp,id).run();
  else if(action==='retry')await context.env.DB.prepare("UPDATE social_publications SET status='READY',next_retry_at=NULL,last_error_code=NULL,last_error_detail=NULL,updated_at=? WHERE id=? AND status='FAILED'").bind(stamp,id).run();
  else if(action==='reschedule'){const date=new Date(body.scheduledFor);if(!Number.isFinite(date.getTime()))return json({error:'Date invalide.'},400);await context.env.DB.prepare("UPDATE social_publications SET status='SCHEDULED',scheduled_for=?,next_retry_at=NULL,updated_at=? WHERE id=? AND status NOT IN ('PUBLISHED','CANCELLED','SKIPPED')").bind(date.toISOString(),stamp,id).run();}
  else if(action==='publish_now'){const result=await processSocialJobs(context.env,{forceId:id});return json({ok:true,result})}
  else return json({error:'Action invalide.'},400);
  await context.env.DB.prepare('INSERT INTO admin_audit_log(id,admin_user_id,action,target_type,target_id,metadata,created_at) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),admin.sub,`social.${action}`,'social_publication',id,'{}',stamp).run();return json({ok:true});
}
